#include "babil.h"

#include "so_util.h"

namespace babil {

#define DECLARE(name) decltype(name) name = nullptr
DECLARE(babilCommand_CE_CameraPos);
DECLARE(babilCommand_CE_SetupCameraMotion);
DECLARE(babilCommand_ClearCountJump);
DECLARE(CoreAudioOutInit);
DECLARE(CoreAudioOutKick);
DECLARE(CoreAudioOutQueueBuffer);
DECLARE(CoreAudioOutRelease);
DECLARE(CoreAudioOutResume);
DECLARE(CoreAudioOutSuspend);
DECLARE(free_count);
DECLARE(FX_Div);
DECLARE(G2_SetWnd0Position);
DECLARE(GX_SetWideMode);
DECLARE(initApp);
DECLARE(malloc_count);
DECLARE(NNS_G2dTickCellAnimation);
DECLARE(NNS_SndPlayerSetPlayerVolume);
DECLARE(NNS_SndPlayerStopSeqBySeqArcIdx);
DECLARE(NNS_SndUpdate);
DECLARE(OS_Printf);
DECLARE(OSi_Panic);
DECLARE(render);
DECLARE(touch);
DECLARE(AchievementChecker::Ctor);
DECLARE(AchievementChecker::Dtor);
DECLARE(AchievementChecker::init);
DECLARE(AchievementChecker::update);
DECLARE(AchievementCheckFuncs::achievementComp);
DECLARE(AchievementCheckFuncs::beatCount);
DECLARE(AchievementCheckFuncs::callFunc);
DECLARE(AchievementCheckFuncs::clearCacheParam);
DECLARE(AchievementCheckFuncs::completedMap);
DECLARE(AchievementCheckFuncs::Ctor);
DECLARE(AchievementCheckFuncs::Dtor);
DECLARE(AchievementCheckFuncs::field);
DECLARE(AchievementCheckFuncs::flag);
DECLARE(AchievementCheckFuncs::flagRange);
DECLARE(AchievementCheckFuncs::getDecant);
DECLARE(AchievementCheckFuncs::getDecantCnt);
DECLARE(AchievementCheckFuncs::getDecantItemName);
DECLARE(AchievementCheckFuncs::getItem);
DECLARE(AchievementCheckFuncs::gill);
DECLARE(AchievementCheckFuncs::hardModeBeat);
DECLARE(AchievementCheckFuncs::init);
DECLARE(AchievementCheckFuncs::learnSummon);
DECLARE(AchievementCheckFuncs::learnSummonCnt);
DECLARE(AchievementCheckFuncs::monsterDictionary);
DECLARE(AchievementCheckFuncs::monsterKillCount);
DECLARE(AchievementCheckFuncs::monsterKillParty);
DECLARE(AchievementCheckFuncs::noCheck);
DECLARE(AchievementCheckFuncs::overPlayerLevel);
DECLARE(AchievementContext::getArchiveReportArray);
DECLARE(AchievementReporter::addParam);
DECLARE(AchievementReporter::Ctor);
DECLARE(AchievementReporter::Dtor);
DECLARE(AchievementReporter::eraseReported);
DECLARE(AchievementReporter::finish);
DECLARE(AchievementReporter::init);
DECLARE(AchievementReporter::isAllReported);
DECLARE(AchievementReporter::isReportedSecondReport);
DECLARE(AchievementReporter::syncSaveData);
DECLARE(AchievementReporter::update);
DECLARE(btl::battleSpeedRate);
DECLARE(btl::AcquiredGoldDrawer::update);
DECLARE(btl::BaseBattleCharacter::isInvincible);
DECLARE(btl::Battle2DManager::ctrlWidgetCheck);
DECLARE(btl::BattleCommandSelector::commandAction);
DECLARE(btl::BattleCommandSelector::initialize);
DECLARE(btl::BattleDebugParameter::flag);
DECLARE(btl::BattleMonsterParty::giftExp);
DECLARE(btl::BattleMonsterParty::giftGold);
DECLARE(btl::BattlePart::doInitialize);
DECLARE(btl::BattlePlayer::playerId);
DECLARE(btl::BattleWin::possessGoldPhase);
DECLARE(btl::CBattleDisplay::doShakeCamera);
DECLARE(CCharacterMng::getCharacterName);
DECLARE(CCharacterMng::getIndexOfSearchingCharacter);
DECLARE(CCharacterMng::setFrameRate);
DECLARE(CCharacterMng::setHidden);
DECLARE(CCharacterMng::setPause);
DECLARE(CCharacterMng::setPosition);
DECLARE(CCharacterMng::setRotation);
DECLARE(CCharacterMng::setShadowAlphaRate);
DECLARE(CCharacterMng::setShadowEnable);
DECLARE(CCharacterMng::setShadowType);
DECLARE(CCharacterMng::setTransparencyRate);
DECLARE(CCharacterMng::startMotion);
DECLARE(common::EfficacyDataConvection::Ctor);
DECLARE(common::EfficacyDataConvection::Dtor);
DECLARE(common::EfficacyDataConvection::getEfficacyData);
DECLARE(common::EfficacyDataConvection::initialize);
DECLARE(common::EfficacyDataConvection::loadBELD);
DECLARE(common::EfficacyDataConvection::terminate);
DECLARE(common::EfficacyDataConvection::unloadBELD);
DECLARE(CTextureDataMng::delData);
DECLARE(CTextureDataMng::end);
DECLARE(CTextureDataMng::getTex);
DECLARE(CTextureDataMng::init);
DECLARE(CTextureDataMng::initValue);
DECLARE(CTextureDataMng::releaseLnkTexVram);
DECLARE(CTextureDataMng::searchDataIndex);
DECLARE(CTextureDataMng::searchNullIndex);
DECLARE(CTextureDataMng::setData);
DECLARE(CTextureDataMng::setData2);
DECLARE(CTextureDataMng::setTextureData);
DECLARE(CTextureDataMng::setupLnkTexVram);
DECLARE(CTextureDataMng::useTexture);
DECLARE(debug::CharaViewerPart::doInitialize);
DECLARE(dgs::DGSMsdGetString);
DECLARE(ds::CPad::repeat);
DECLARE(ds::CVram::releasePlttVramMng);
DECLARE(ds::CVram::releaseTexVramMng);
DECLARE(ds::CVram::setupPlttVramMng);
DECLARE(ds::CVram::setupTexVramMng);
DECLARE(ds::snd::dssndInitialize);
DECLARE(ds::snd::dssndUnloadBGM1);
DECLARE(ds::snd::dssndUnloadBGM2);
DECLARE(ds::snd::dssndUnloadBGMAll);
DECLARE(ds::snd::dssndUnloadSE1);
DECLARE(ds::snd::dssndUnloadSE2);
DECLARE(ds::snd::dssndUnloadSEAll);
DECLARE(ds::snd::dssndUpdate);
DECLARE(ds::snd::BGMHandle::Ctor);
DECLARE(ds::snd::BGMHandle::Dtor);
DECLARE(ds::snd::BGMHandle::forceReleaseSequence);
DECLARE(ds::snd::BGMHandle::getBGMEnable);
DECLARE(ds::snd::BGMHandle::IsPlaying);
DECLARE(ds::snd::BGMHandle::MoveVolume);
DECLARE(ds::snd::BGMHandle::Pause);
DECLARE(ds::snd::BGMHandle::Play);
DECLARE(ds::snd::BGMHandle::PlayV);
DECLARE(ds::snd::BGMHandle::seqNo);
DECLARE(ds::snd::BGMHandle::setBGMEnable);
DECLARE(ds::snd::BGMHandle::setTempo);
DECLARE(ds::snd::BGMHandle::SetVolume);
DECLARE(ds::snd::BGMHandle::Stop);
DECLARE(ds::snd::DSSoundHeap::dsshFinalize);
DECLARE(ds::snd::SEHandle::Ctor);
DECLARE(ds::snd::SEHandle::Dtor);
DECLARE(ds::snd::SEHandle::IsPlaying);
DECLARE(ds::snd::SEHandle::MoveVolume);
DECLARE(ds::snd::SEHandle::Play);
DECLARE(ds::snd::SEHandle::PlayFadeIn);
DECLARE(ds::snd::SEHandle::setPan);
DECLARE(ds::snd::SEHandle::setPanRange);
DECLARE(ds::snd::SEHandle::setPitch);
DECLARE(ds::snd::SEHandle::setTempo);
DECLARE(ds::snd::SEHandle::setVolume);
DECLARE(ds::snd::SEHandle::stop);
DECLARE(ds::sys3d::CAnimation::ctor);
DECLARE(ds::sys3d::CAnimation::getFrameRate);
DECLARE(ds::sys3d::CAnimation::setFrameRate);
DECLARE(ds::sys3d::CAnimation::setup);
DECLARE(ds::sys3d::CCamera::setFOV);
DECLARE(ds::sys3d::CModelTexture::bindMdl);
DECLARE(ds::sys3d::CModelTexture::bindMdlSet);
DECLARE(ds::sys3d::CModelTexture::bindMdlToPltt);
DECLARE(ds::sys3d::CModelTexture::bindMdlToPlttByName);
DECLARE(ds::sys3d::CModelTexture::bindMdlToTex);
DECLARE(ds::sys3d::CModelTexture::bindMdlToTexByName);
DECLARE(ds::sys3d::CModelTexture::bindTexPlt);
DECLARE(ds::sys3d::CModelTexture::cleanup);
DECLARE(ds::sys3d::CModelTexture::clearValue);
DECLARE(ds::sys3d::CModelTexture::Ctor);
DECLARE(ds::sys3d::CModelTexture::Dtor);
DECLARE(ds::sys3d::CModelTexture::isModelTexture);
DECLARE(ds::sys3d::CModelTexture::releaseMdl);
DECLARE(ds::sys3d::CModelTexture::releaseMdlSet);
DECLARE(ds::sys3d::CModelTexture::releaseMdlToPltt);
DECLARE(ds::sys3d::CModelTexture::releaseMdlToPlttByName);
DECLARE(ds::sys3d::CModelTexture::releaseMdlToTex);
DECLARE(ds::sys3d::CModelTexture::releaseMdlToTexByName);
DECLARE(ds::sys3d::CModelTexture::releaseResource);
DECLARE(ds::sys3d::CModelTexture::reqReleaseResource);
DECLARE(ds::sys3d::CModelTexture::setup);
DECLARE(ds::sys3d::CModelTexture::tdlhCompletion);
DECLARE(ds::sys3d::CMotSet::getFrameRate);
DECLARE(ds::sys3d::CMotSet::setFrameRate);
DECLARE(egs::GilbartInitialize);
DECLARE(egs::GilbartIsEndOfPlayVoice);
DECLARE(egs::GilbartIsPlaying);
DECLARE(egs::GilbartPauseVoice);
DECLARE(egs::GilbartPlayVoice);
DECLARE(egs::GilbartProcess);
DECLARE(egs::GilbartSetVolume);
DECLARE(egs::GilbartStatus);
DECLARE(egs::GilbartStopVoice);
DECLARE(egs::GilbartTerminate);
DECLARE(evt::EventCamera::startCameraMotion);
DECLARE(FlagManager::Ctor);
DECLARE(FlagManager::Dtor);
DECLARE(FlagManager::get);
DECLARE(FlagManager::reset);
DECLARE(FlagManager::reverse);
DECLARE(FlagManager::set);
DECLARE(FlagManager::singleton);
DECLARE(Font::initFont);
DECLARE(itm::EquipParameter::canEquip);
DECLARE(itm::ItemManager::consumptionParameter);
DECLARE(itm::ItemManager::equipParameter);
DECLARE(itm::ItemManager::free);
DECLARE(itm::ItemManager::importantParameter);
DECLARE(itm::ItemManager::itemCategory);
DECLARE(itm::ItemManager::itemParameter);
DECLARE(itm::ItemManager::load);
DECLARE(itm::ItemManager::protectionParameter);
DECLARE(itm::ItemManager::weaponParameter);
DECLARE(itm::PossessionItemManager::eraseAllImportantItem);
DECLARE(itm::PossessionItemManager::eraseAllNormalItem);
DECLARE(itm::PossessionItemManager::eraseItem);
DECLARE(itm::PossessionItemManager::importantItem);
DECLARE(itm::PossessionItemManager::importantItemNum);
DECLARE(itm::PossessionItemManager::initialize);
DECLARE(itm::PossessionItemManager::itemAllNum);
DECLARE(itm::PossessionItemManager::normalItem);
DECLARE(itm::PossessionItemManager::normalItemNum);
DECLARE(itm::PossessionItemManager::reserveCancel);
DECLARE(itm::PossessionItemManager::resetImportantItemId);
DECLARE(itm::PossessionItemManager::resetItemId);
DECLARE(itm::PossessionItemManager::searchImportantItem);
DECLARE(itm::PossessionItemManager::searchNormalItem);
DECLARE(itm::PossessionItemManager::storeImportantItem);
DECLARE(itm::PossessionItemManager::storeItem);
DECLARE(itm::PossessionItemManager::swapItem);
DECLARE(map2d::NaviMap::MapOff);
DECLARE(map2d::NaviMap::MapOn);
DECLARE(map2d::NaviMap::NaviMapDrawOff);
DECLARE(map2d::NaviMap::setAlpha);
DECLARE(menu::playSECommon);
DECLARE(mon::MonsterManager::acceptMonsterManiaData);
DECLARE(mon::MonsterManager::actionCondition);
DECLARE(mon::MonsterManager::ai);
DECLARE(mon::MonsterManager::counter);
DECLARE(mon::MonsterManager::dropItem);
DECLARE(mon::MonsterManager::effectsInfo);
DECLARE(mon::MonsterManager::free);
DECLARE(mon::MonsterManager::load);
DECLARE(mon::MonsterManager::monsterManiaManager);
DECLARE(mon::MonsterManager::monsterParameter);
DECLARE(mon::MonsterManager::normalAttack);
DECLARE(mon::MonsterManager::octmanmosLegInfo);
DECLARE(mon::MonsterManager::offset);
DECLARE(mon::MonsterManager::sendMonsterManiaData);
DECLARE(mon::MonsterManager::setMonsterIdForMonsterManaia);
DECLARE(mon::MonsterManager::turnAction);
DECLARE(mon::MonsterManiaManager::clearMonsterMania);
DECLARE(mon::MonsterManiaManager::kill);
DECLARE(mon::MonsterManiaManager::monsterMania);
DECLARE(mon::MonsterManiaManager::onEncount);
DECLARE(mon::MonsterManiaManager::onLibrary);
DECLARE(mon::MonsterManiaManager::setMonsterManiaForMonsterID);
DECLARE(mr::getCompleteRate);
DECLARE(mr::MonsterRefDataManager::Ctor);
DECLARE(mr::MonsterRefDataManager::Dtor);
DECLARE(mr::MonsterRefDataManager::free);
DECLARE(mr::MonsterRefDataManager::load);
DECLARE(mr::MonsterRefDataManager::monsterReference);
DECLARE(mr::MonsterRefDataManager::monsterReferenceFromIndex);
DECLARE(pl::LearningAbilityManager::clear);
DECLARE(pl::LearningAbilityManager::forget);
DECLARE(pl::LearningAbilityManager::initialize);
DECLARE(pl::LearningAbilityManager::isLearning);
DECLARE(pl::LearningAbilityManager::isMagicTypesAbility);
DECLARE(pl::LearningAbilityManager::isOn);
DECLARE(pl::LearningAbilityManager::learn);
DECLARE(pl::LearningAbilityManager::learnForDebug);
DECLARE(pl::LearningAbilityManager::learningMagicTypesNumber);
DECLARE(pl::LearningAbilityManager::off);
DECLARE(pl::LearningAbilityManager::on);
DECLARE(pl::LearningAbilityManager::setContents);
DECLARE(pl::Player::abilityBouns);
DECLARE(pl::Player::addEquipmentBonus);
DECLARE(pl::Player::addMagicDefense);
DECLARE(pl::Player::addPhysicsDefense_ib);
DECLARE(pl::Player::addPhysicsDefense_Pb);
DECLARE(pl::Player::adjustAbility);
DECLARE(pl::Player::attachEquipmentSymbol);
DECLARE(pl::Player::attachEquipmentSymbolOne);
DECLARE(pl::Player::avoidance);
DECLARE(pl::Player::bodyAndBonus);
DECLARE(pl::Player::bodyAndBonus_BP);
DECLARE(pl::Player::calcBonus);
DECLARE(pl::Player::calcHpColor);
DECLARE(pl::Player::calcMagicDefense);
DECLARE(pl::Player::calcPhysicsDefense);
DECLARE(pl::Player::canEquip);
DECLARE(pl::Player::canEquipArrow);
DECLARE(pl::Player::canEquipBow);
DECLARE(pl::Player::canEquipHarp);
DECLARE(pl::Player::canEquipWeapon);
DECLARE(pl::Player::canGivenExp);
DECLARE(pl::Player::canWinningDirection);
DECLARE(pl::Player::changeStonePalette);
DECLARE(pl::Player::changeStonePaletteForEvent);
DECLARE(pl::Player::checkHpColor);
DECLARE(pl::Player::clearCommand);
DECLARE(pl::Player::condition);
DECLARE(pl::Player::Ctor);
DECLARE(pl::Player::decantLevel);
DECLARE(pl::Player::defaultMaxHp);
DECLARE(pl::Player::defaultMaxMp);
DECLARE(pl::Player::deftness);
DECLARE(pl::Player::difference);
DECLARE(pl::Player::doEquip);
DECLARE(pl::Player::Dtor);
DECLARE(pl::Player::equipmentAttach);
DECLARE(pl::Player::equipmentBounsHP);
DECLARE(pl::Player::equipmentSymbolVisibility);
DECLARE(pl::Player::equipMenuParameter);
DECLARE(pl::Player::equipParameter);
DECLARE(pl::Player::exp);
DECLARE(pl::Player::fine);
DECLARE(pl::Player::forgetAbility_AI);
DECLARE(pl::Player::forgetAbility_i);
DECLARE(pl::Player::forgetAllAbilityForDebug);
DECLARE(pl::Player::forgetAllBlackMagicForDebug);
DECLARE(pl::Player::forgetAllNinjutsuForDebug);
DECLARE(pl::Player::forgetAllSongForDebug);
DECLARE(pl::Player::forgetAllSummonForDebug);
DECLARE(pl::Player::forgetAllWhiteMagicForDebug);
DECLARE(pl::Player::forgetLearnedMagicByEvent);
DECLARE(pl::Player::growParameter);
DECLARE(pl::Player::hp);
DECLARE(pl::Player::initialize);
DECLARE(pl::Player::initializeCommand);
DECLARE(pl::Player::initializeDefaultCommand);
DECLARE(pl::Player::initializeName);
DECLARE(pl::Player::isCanEquipProtection);
DECLARE(pl::Player::isCommand);
DECLARE(pl::Player::isEquipable);
DECLARE(pl::Player::isEquipedItemOnAllPoints);
DECLARE(pl::Player::isEquipedItemOnPoint);
DECLARE(pl::Player::isEquipItem);
DECLARE(pl::Player::isEquipMetal);
DECLARE(pl::Player::isEquippedBow);
DECLARE(pl::Player::isFinishAttack);
DECLARE(pl::Player::isHand);
DECLARE(pl::Player::isHandCheck);
DECLARE(pl::Player::isHealing);
DECLARE(pl::Player::isKnowledgeInCommand);
DECLARE(pl::Player::isUseMagic_AI);
DECLARE(pl::Player::isUseMagic_BM);
DECLARE(pl::Player::isUseMagicCharacter);
DECLARE(pl::Player::learnAbility_AI);
DECLARE(pl::Player::learnAbility_ii);
DECLARE(pl::Player::learnAbilityForDebug);
DECLARE(pl::Player::learnAllAbilityForDebug);
DECLARE(pl::Player::learnAllBlackMagicForDebug);
DECLARE(pl::Player::learnAllNinjutsuForDebug);
DECLARE(pl::Player::learnAllSongForDebug);
DECLARE(pl::Player::learnAllSummonForDebug);
DECLARE(pl::Player::learnAllWhiteMagicForDebug);
DECLARE(pl::Player::learningAbility);
DECLARE(pl::Player::level);
DECLARE(pl::Player::levelDown);
DECLARE(pl::Player::levelUp);
DECLARE(pl::Player::listupCommand);
DECLARE(pl::Player::listupCommandMagic);
DECLARE(pl::Player::listupCommandNormal);
DECLARE(pl::Player::magicDefense);
DECLARE(pl::Player::magicDefensePower);
DECLARE(pl::Player::mp);
DECLARE(pl::Player::physicsAttack);
DECLARE(pl::Player::physicsDefense);
DECLARE(pl::Player::playerAbilityManager);
DECLARE(pl::Player::recoverHPandMP);
DECLARE(pl::Player::releaseEquipItem);
DECLARE(pl::Player::removeEquipmentSymbol);
DECLARE(pl::Player::removeEquipmentSymbolOne);
DECLARE(pl::Player::saveParameter);
DECLARE(pl::Player::setExp);
DECLARE(pl::Player::setHp);
DECLARE(pl::Player::setParameter);
DECLARE(pl::Player::setPhysicsAttack);
DECLARE(pl::Player::spendMp);
DECLARE(pl::Player::stonePaletteName);
DECLARE(pl::Player::updateCondition);
DECLARE(pl::Player::updateEquipmentSymbol);
DECLARE(pl::Player::updateParameter);
DECLARE(pl::Player::useApple);
DECLARE(pl::Player::useSomaDrop);
DECLARE(pl::PlayerParty::abilityBouns);
DECLARE(pl::PlayerParty::abilityList);
DECLARE(pl::PlayerParty::addItem);
DECLARE(pl::PlayerParty::addMember);
DECLARE(pl::PlayerParty::aliveNumber);
DECLARE(pl::PlayerParty::averageLevel);
DECLARE(pl::PlayerParty::changeFormation);
DECLARE(pl::PlayerParty::changeMember);
DECLARE(pl::PlayerParty::changeMemberForOrder);
DECLARE(pl::PlayerParty::changeStonePalette);
DECLARE(pl::PlayerParty::changeStonePaletteForEvent);
DECLARE(pl::PlayerParty::clearBattleCommand);
DECLARE(pl::PlayerParty::clearBattleCommandPlayer);
DECLARE(pl::PlayerParty::clearBattleCondition);
DECLARE(pl::PlayerParty::Ctor);
DECLARE(pl::PlayerParty::Dtor);
DECLARE(pl::PlayerParty::fineAll);
DECLARE(pl::PlayerParty::formation);
DECLARE(pl::PlayerParty::free);
DECLARE(pl::PlayerParty::initForNewgame);
DECLARE(pl::PlayerParty::initialize);
DECLARE(pl::PlayerParty::initializeName);
DECLARE(pl::PlayerParty::isCommand);
DECLARE(pl::PlayerParty::isEnableMember);
DECLARE(pl::PlayerParty::isFrogAll);
DECLARE(pl::PlayerParty::isJoinedParty);
DECLARE(pl::PlayerParty::isLearnByLevelUp);
DECLARE(pl::PlayerParty::isLilliputAll);
DECLARE(pl::PlayerParty::isPartyFull);
DECLARE(pl::PlayerParty::layoutSceneParameter);
DECLARE(pl::PlayerParty::learningAbility);
DECLARE(pl::PlayerParty::levelParameter);
DECLARE(pl::PlayerParty::listupCommand);
DECLARE(pl::PlayerParty::load);
DECLARE(pl::PlayerParty::loadComposition);
DECLARE(pl::PlayerParty::member);
DECLARE(pl::PlayerParty::memberForOrder);
DECLARE(pl::PlayerParty::memberOrder);
DECLARE(pl::PlayerParty::normalAttack);
DECLARE(pl::PlayerParty::normalMagic);
DECLARE(pl::PlayerParty::partyMemberEnableNumber);
DECLARE(pl::PlayerParty::player);
DECLARE(pl::PlayerParty::releaseMember);
DECLARE(pl::PlayerParty::saveComposition);
DECLARE(pl::PlayerParty::setFormation);
DECLARE(pl::PlayerParty::setMemberForOrder);
DECLARE(pl::PlayerParty::setSaveStartCommand);
DECLARE(pl::PlayerParty::weaponOffsetParameter);
DECLARE(ScriptEngine::getByte);
DECLARE(ScriptEngine::getDword);
DECLARE(ScriptEngine::jump);
DECLARE(sys::GameParameter::abilityName);
DECLARE(sys::GameParameter::changeFormation);
DECLARE(sys::GameParameter::coverNum);
DECLARE(sys::GameParameter::Ctor);
DECLARE(sys::GameParameter::fieldSymbolID);
DECLARE(sys::GameParameter::formation);
DECLARE(sys::GameParameter::gameClearCount);
DECLARE(sys::GameParameter::getBlackChocoboHome);
DECLARE(sys::GameParameter::getDesionDataValidity);
DECLARE(sys::GameParameter::getDesionMapName);
DECLARE(sys::GameParameter::getDesionPosition);
DECLARE(sys::GameParameter::getDesionRot);
DECLARE(sys::GameParameter::getMagishipMoonChipX);
DECLARE(sys::GameParameter::getMagishipMoonChipZ);
DECLARE(sys::GameParameter::getMagishipPosOffsetOnMoonChip);
DECLARE(sys::GameParameter::getMagshipEarthPos);
DECLARE(sys::GameParameter::getMagshipMoonPos);
DECLARE(sys::GameParameter::getMapName);
DECLARE(sys::GameParameter::getPassagePoint2);
DECLARE(sys::GameParameter::getSaveNo);
DECLARE(sys::GameParameter::getSaveNum);
DECLARE(sys::GameParameter::getTVMode);
DECLARE(sys::GameParameter::getWorldPlayerPosition);
DECLARE(sys::GameParameter::getWorldPlayerRotation);
DECLARE(sys::GameParameter::getWorldTelepoMapName);
DECLARE(sys::GameParameter::getWorldTelepoPosition);
DECLARE(sys::GameParameter::getWorldTelepoRotation);
DECLARE(sys::GameParameter::getWorldVehiclePosition);
DECLARE(sys::GameParameter::getWorldVehicleRotation);
DECLARE(sys::GameParameter::getWorldVehicleStay);
DECLARE(sys::GameParameter::gold);
DECLARE(sys::GameParameter::gpCopy);
DECLARE(sys::GameParameter::gpInitialize);
DECLARE(sys::GameParameter::gpLoadDataReflect);
DECLARE(sys::GameParameter::incrementCoverNum);
DECLARE(sys::GameParameter::incrementGameClearCount);
DECLARE(sys::GameParameter::isAutoMode);
DECLARE(sys::GameParameter::isCloudGuideShowed);
DECLARE(sys::GameParameter::isDash);
DECLARE(sys::GameParameter::isPlayVoice);
DECLARE(sys::GameParameter::isShowConteEventTelop);
DECLARE(sys::GameParameter::isTVMode);
DECLARE(sys::GameParameter::item);
DECLARE(sys::GameParameter::monsterManiaManager);
DECLARE(sys::GameParameter::musicPlayerMode);
DECLARE(sys::GameParameter::playerName);
DECLARE(sys::GameParameter::playerSaveParameter);
DECLARE(sys::GameParameter::playTime);
DECLARE(sys::GameParameter::previousSaveData);
DECLARE(sys::GameParameter::prevSaveForFlag);
DECLARE(sys::GameParameter::prevSaveForNavimap);
DECLARE(sys::GameParameter::prevSaveForNavimapAsync);
DECLARE(sys::GameParameter::prevSaveForTime);
DECLARE(sys::GameParameter::print);
DECLARE(sys::GameParameter::printMemory);
DECLARE(sys::GameParameter::reflectForFlag);
DECLARE(sys::GameParameter::reflectForNavimap2);
DECLARE(sys::GameParameter::reflectForTime);
DECLARE(sys::GameParameter::rrc);
DECLARE(sys::GameParameter::setAutoMode);
DECLARE(sys::GameParameter::setBlackChocoboHome);
DECLARE(sys::GameParameter::setCloudGuideShowed);
DECLARE(sys::GameParameter::setDash);
DECLARE(sys::GameParameter::setDesionDataValidity);
DECLARE(sys::GameParameter::setDesionMapName);
DECLARE(sys::GameParameter::setDesionPosition);
DECLARE(sys::GameParameter::setDesionRot);
DECLARE(sys::GameParameter::setFieldSymbolID);
DECLARE(sys::GameParameter::setFormation);
DECLARE(sys::GameParameter::setMagishipMoonChipX);
DECLARE(sys::GameParameter::setMagishipMoonChipZ);
DECLARE(sys::GameParameter::setMagishipPosOffsetOnMoonChip);
DECLARE(sys::GameParameter::setMagshipEarthPos);
DECLARE(sys::GameParameter::setMagshipMoonPos);
DECLARE(sys::GameParameter::setMapName);
DECLARE(sys::GameParameter::setMonsterManiaManager);
DECLARE(sys::GameParameter::setPartsHeaderStr);
DECLARE(sys::GameParameter::setPassagePoint2);
DECLARE(sys::GameParameter::setPlayTime);
DECLARE(sys::GameParameter::setResetCloudGuideShowed);
DECLARE(sys::GameParameter::setSaveNo);
DECLARE(sys::GameParameter::setSaveNum);
DECLARE(sys::GameParameter::setTVMode);
DECLARE(sys::GameParameter::setWorldPlayerPosition);
DECLARE(sys::GameParameter::setWorldPlayerRotation);
DECLARE(sys::GameParameter::setWorldTelepoMapName);
DECLARE(sys::GameParameter::setWorldTelepoPosition);
DECLARE(sys::GameParameter::setWorldTelepoRotation);
DECLARE(sys::GameParameter::setWorldVehiclePosition);
DECLARE(sys::GameParameter::setWorldVehicleRotation);
DECLARE(sys::GameParameter::setWorldVehicleStay);
DECLARE(sys::GameParameter::summonSaveParameter);
DECLARE(sys::GGlobal::getCurrentPart);
DECLARE(sys::GGlobal::setNextPart);
DECLARE(title::TitleContents::update);
DECLARE(title::TitleSubState::update);
DECLARE(ui::CWidgetMng::addWidget);
DECLARE(ui::CWidgetMng::cleanWidget);
DECLARE(ui::CWidgetMng::DefaultPadKeyFunc);
DECLARE(ui::CWidgetMng::DefaultPadKeyFunc_Line2);
DECLARE(ui::CWidgetMng::DefaultPadKeyFunc_Line3);
DECLARE(ui::CWidgetMng::DefaultPadKeyFunc_LineMulti);
DECLARE(ui::CWidgetMng::deleteWidget);
DECLARE(ui::CWidgetMng::deleteWidgetRange);
DECLARE(ui::CWidgetMng::draw);
DECLARE(ui::CWidgetMng::drawWidget);
DECLARE(ui::CWidgetMng::execute);
DECLARE(ui::CWidgetMng::findWidget);
DECLARE(ui::CWidgetMng::getActiveCursor);
DECLARE(ui::CWidgetMng::getActiveCursorItem);
DECLARE(ui::CWidgetMng::getActiveCursorListMax);
DECLARE(ui::CWidgetMng::getCursorItem);
DECLARE(ui::CWidgetMng::getListMax);
DECLARE(ui::CWidgetMng::initialize);
DECLARE(ui::CWidgetMng::moveSlide);
DECLARE(ui::CWidgetMng::moveWidget);
DECLARE(ui::CWidgetMng::setCursor);
DECLARE(ui::CWidgetMng::setDefaultPadKeyFunc);
DECLARE(ui::CWidgetMng::setDragState);
DECLARE(ui::CWidgetMng::setListMax);
DECLARE(ui::CWidgetMng::setScroll);
DECLARE(ui::CWidgetMng::setScrollPos);
DECLARE(ui::CWidgetMng::setScrollRect);
DECLARE(ui::CWidgetMng::setSlide);
DECLARE(ui::CWidgetMng::setWidgetEnable);
DECLARE(ui::CWidgetMng::setWidgetHilight);
DECLARE(ui::CWidgetMng::terminate);
DECLARE(world::canChangeSymbol);
DECLARE(world::disableSPSetting);
DECLARE(world::enableSPSetting);
DECLARE(world::MSSTextScreenClear);
DECLARE(world::searchNextSymbolByCharacterIDBackward);
DECLARE(world::searchNextSymbolByCharacterIDForward);
DECLARE(world::CCameraVibration::ccbUpdate);
DECLARE(world::CCameraVibration::startVibration);
DECLARE(world::MSSConfig::mssInitialize);
DECLARE(world::MSSConfig::mssProcess);
DECLARE(world::WorldState::wsGetString);
DECLARE(world::WorldState::wsSetEnd);
DECLARE(world::WorldStateScheduler::wssAddStateSchedule);
DECLARE(world::WorldStateScheduler::wssGetCurrentState);
DECLARE(world::WorldStateScheduler::wssInitialize);
DECLARE(world::WorldTask::deleteTask);
DECLARE(world::WorldTask::queryTask);
DECLARE(world::WSMove::wsIsMenuOpen);
DECLARE(world::WSMove::wsmEncount);
DECLARE(world::WSMove::WSMove);
DECLARE(world::WSVehicleMove::wsProcess);
DECLARE(ys::Condition::isNotBattleCondition);
DECLARE(characterMng);
DECLARE(fontScale);
DECLARE(g_env);
DECLARE(LCD_HEIGHT);
DECLARE(LCD_WIDTH);
DECLARE(memCount);
DECLARE(texCount);
DECLARE(AchievementCheckFuncs::DecantItemTbl);
DECLARE(AchievementContext::instance_);
DECLARE(btl::Battle2DManager::instance_);
DECLARE(btl::BattlePart::instance_);
DECLARE(common::EfficacyDataConvection::instance_);
DECLARE(ds::g_Pad);
DECLARE(ds::CVram::m_instance);
DECLARE(ds::snd::g_SoundHeapBGM);
DECLARE(ds::snd::g_SoundHeapSE);
DECLARE(FlagManager::_instance);
DECLARE(itm::ItemManager::instance_);
DECLARE(map2d::NAVI_MAP_TASK_NAME);
DECLARE(mon::MonsterManager::instance_);
DECLARE(mr::MRDMng);
DECLARE(part::WorldPart::wpInstance_);
DECLARE(pl::LearningAbilityManager::ARRAY_SIZE);
DECLARE(pl::LearningAbilityManager::FLAG_OFFSET);
DECLARE(pl::LearningAbilityManager::FLAG_SIZE);
DECLARE(pl::PlayerParty::InvalidPlayer);
DECLARE(pl::PlayerParty::playerPartyInstance_);
DECLARE(sys::GameParameter::gpInstance_);
DECLARE(sys::GGlobal::heapBGM_);
DECLARE(sys::GGlobal::heapSE_);
DECLARE(sys::GGlobal::heapSound_);
DECLARE(ui::g_WidgetMng);
#undef DECLARE

#define GET_SYMBOL(name, symbol) name = reinterpret_cast<decltype(name)>(so::findAddr_rx(symbol))
void init() {
    GET_SYMBOL(babilCommand_CE_CameraPos, "_Z25babilCommand_CE_CameraPosR12ScriptEngine");
    GET_SYMBOL(babilCommand_CE_SetupCameraMotion, "_Z33babilCommand_CE_SetupCameraMotionR12ScriptEngine");
    GET_SYMBOL(babilCommand_ClearCountJump, "_Z27babilCommand_ClearCountJumpR12ScriptEngine");
    GET_SYMBOL(CoreAudioOutInit, "CoreAudioOutInit");
    GET_SYMBOL(CoreAudioOutKick, "CoreAudioOutKick");
    GET_SYMBOL(CoreAudioOutQueueBuffer, "CoreAudioOutQueueBuffer");
    GET_SYMBOL(CoreAudioOutRelease, "CoreAudioOutRelease");
    GET_SYMBOL(CoreAudioOutResume, "CoreAudioOutResume");
    GET_SYMBOL(CoreAudioOutSuspend, "CoreAudioOutSuspend");
    GET_SYMBOL(free_count, "_Z10free_countPv");
    GET_SYMBOL(FX_Div, "_Z6FX_Divii");
    GET_SYMBOL(G2_SetWnd0Position, "_Z18G2_SetWnd0Positioniiii");
    GET_SYMBOL(GX_SetWideMode, "_Z14GX_SetWideModeib");
    GET_SYMBOL(initApp, "_Z7initAppP7_JNIEnv");
    GET_SYMBOL(malloc_count, "_Z12malloc_countm");
    GET_SYMBOL(NNS_G2dTickCellAnimation, "_Z24NNS_G2dTickCellAnimationP19NNSG2dCellAnimationi");
    GET_SYMBOL(NNS_SndPlayerSetPlayerVolume, "_Z28NNS_SndPlayerSetPlayerVolumeii");
    GET_SYMBOL(NNS_SndPlayerStopSeqBySeqArcIdx, "_Z31NNS_SndPlayerStopSeqBySeqArcIdxiii");
    GET_SYMBOL(NNS_SndUpdate, "_Z13NNS_SndUpdatev");
    GET_SYMBOL(OS_Printf, "_Z9OS_PrintfPKcz");
    GET_SYMBOL(OSi_Panic, "_Z9OSi_PanicPKciS0_z");
    GET_SYMBOL(render, "render");
    GET_SYMBOL(touch, "touch");
    GET_SYMBOL(AchievementChecker::Ctor, "_ZN18AchievementCheckerC1Ev");
    GET_SYMBOL(AchievementChecker::Dtor, "_ZN18AchievementCheckerD1Ev");
    GET_SYMBOL(AchievementChecker::init, "_ZN18AchievementChecker4initEP19AchievementReporterP19AchievementResourceP21AchievementCheckFuncs");
    GET_SYMBOL(AchievementChecker::update, "_ZN18AchievementChecker6updateE25enAchievementCheckTimings");
    GET_SYMBOL(AchievementCheckFuncs::achievementComp, "_ZN21AchievementCheckFuncs15achievementCompEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::beatCount, "_ZN21AchievementCheckFuncs9beatCountEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::callFunc, "_ZN21AchievementCheckFuncs8callFuncEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::clearCacheParam, "_ZN21AchievementCheckFuncs15clearCacheParamEv");
    GET_SYMBOL(AchievementCheckFuncs::completedMap, "_ZN21AchievementCheckFuncs12completedMapEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::Ctor, "_ZN21AchievementCheckFuncsC1Ev");
    GET_SYMBOL(AchievementCheckFuncs::Dtor, "_ZN21AchievementCheckFuncsD1Ev");
    GET_SYMBOL(AchievementCheckFuncs::field, "_ZN21AchievementCheckFuncs5fieldEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::flag, "_ZN21AchievementCheckFuncs4flagEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::flagRange, "_ZN21AchievementCheckFuncs9flagRangeEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::getDecant, "_ZN21AchievementCheckFuncs9getDecantEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::getDecantCnt, "_ZN21AchievementCheckFuncs12getDecantCntEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::getDecantItemName, "_ZN21AchievementCheckFuncs17getDecantItemNameEiPc");
    GET_SYMBOL(AchievementCheckFuncs::getItem, "_ZN21AchievementCheckFuncs7getItemEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::gill, "_ZN21AchievementCheckFuncs4gillEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::hardModeBeat, "_ZN21AchievementCheckFuncs12hardModeBeatEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::init, "_ZN21AchievementCheckFuncs4initEP19AchievementResource");
    GET_SYMBOL(AchievementCheckFuncs::learnSummon, "_ZN21AchievementCheckFuncs11learnSummonEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::learnSummonCnt, "_ZN21AchievementCheckFuncs14learnSummonCntEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::monsterDictionary, "_ZN21AchievementCheckFuncs17monsterDictionaryEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::monsterKillCount, "_ZN21AchievementCheckFuncs16monsterKillCountEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::monsterKillParty, "_ZN21AchievementCheckFuncs16monsterKillPartyEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::noCheck, "_ZN21AchievementCheckFuncs7noCheckEP16AchievementParam");
    GET_SYMBOL(AchievementCheckFuncs::overPlayerLevel, "_ZN21AchievementCheckFuncs15overPlayerLevelEP16AchievementParam");
    GET_SYMBOL(AchievementContext::getArchiveReportArray, "_ZN18AchievementContext21getArchiveReportArrayEv");
    GET_SYMBOL(AchievementReporter::addParam, "_ZN19AchievementReporter8addParamER16AchievementParam");
    GET_SYMBOL(AchievementReporter::Ctor, "_ZN19AchievementReporterC1Ev");
    GET_SYMBOL(AchievementReporter::Dtor, "_ZN19AchievementReporterD1Ev");
    GET_SYMBOL(AchievementReporter::eraseReported, "_ZN19AchievementReporter13eraseReportedEv");
    GET_SYMBOL(AchievementReporter::finish, "_ZN19AchievementReporter6finishEPKc");
    GET_SYMBOL(AchievementReporter::init, "_ZN19AchievementReporter4initEv");
    GET_SYMBOL(AchievementReporter::isAllReported, "_ZNK19AchievementReporter13isAllReportedEv");
    GET_SYMBOL(AchievementReporter::isReportedSecondReport, "_ZN19AchievementReporter22isReportedSecondReportEv");
    GET_SYMBOL(AchievementReporter::syncSaveData, "_ZN19AchievementReporter12syncSaveDataEP19AchievementResource");
    GET_SYMBOL(AchievementReporter::update, "_ZN19AchievementReporter6updateEv");
    GET_SYMBOL(btl::battleSpeedRate, "_ZN3btl15battleSpeedRateEv");
    GET_SYMBOL(btl::AcquiredGoldDrawer::update, "_ZN3btl18AcquiredGoldDrawer6updateEv");
    GET_SYMBOL(btl::BaseBattleCharacter::isInvincible, "_ZN3btl19BaseBattleCharacter12isInvincibleEv");
    GET_SYMBOL(btl::Battle2DManager::ctrlWidgetCheck, "_ZN3btl15Battle2DManager15ctrlWidgetCheckENS0_16WIDGET_CTRL_TYPEE");
    GET_SYMBOL(btl::BattleCommandSelector::commandAction, "_ZN3btl21BattleCommandSelector13commandActionERNS_12BattleSystemEN6common10ABILITY_IDEc");
    GET_SYMBOL(btl::BattleCommandSelector::initialize, "_ZN3btl21BattleCommandSelector10initializeERNS_12BattleSystemEPNS_12BattlePlayerE");
    GET_SYMBOL(btl::BattleDebugParameter::flag, "_ZN3btl20BattleDebugParameter4flagENS_10DEBUG_FLAGE");
    GET_SYMBOL(btl::BattleMonsterParty::giftExp, "_ZN3btl18BattleMonsterParty7giftExpEv");
    GET_SYMBOL(btl::BattleMonsterParty::giftGold, "_ZN3btl18BattleMonsterParty8giftGoldEv");
    GET_SYMBOL(btl::BattlePart::doInitialize, "_ZN3btl10BattlePart12doInitializeEv");
    GET_SYMBOL(btl::BattlePlayer::playerId, "_ZN3btl12BattlePlayer8playerIdEv");
    GET_SYMBOL(btl::BattleWin::possessGoldPhase, "_ZN3btl9BattleWin16possessGoldPhaseERNS_12BattleSystemE");
    GET_SYMBOL(btl::CBattleDisplay::doShakeCamera, "_ZN3btl14CBattleDisplay13doShakeCameraEv");
    GET_SYMBOL(CCharacterMng::getCharacterName, "_ZN13CCharacterMng16getCharacterNameEi");
    GET_SYMBOL(CCharacterMng::getIndexOfSearchingCharacter, "_ZN13CCharacterMng28getIndexOfSearchingCharacterEv");
    GET_SYMBOL(CCharacterMng::setFrameRate, "_ZN13CCharacterMng12setFrameRateEi");
    GET_SYMBOL(CCharacterMng::setHidden, "_ZN13CCharacterMng9setHiddenEib");
    GET_SYMBOL(CCharacterMng::setPause, "_ZN13CCharacterMng8setPauseEibN2ds5sys3d8CAnimSet6enTYPEE");
    GET_SYMBOL(CCharacterMng::setPosition, "_ZN13CCharacterMng11setPositionEiRK7VecFx32");
    GET_SYMBOL(CCharacterMng::setRotation, "_ZN13CCharacterMng11setRotationEittt");
    GET_SYMBOL(CCharacterMng::setShadowAlphaRate, "_ZN13CCharacterMng18setShadowAlphaRateEii");
    GET_SYMBOL(CCharacterMng::setShadowEnable, "_ZN13CCharacterMng15setShadowEnableEib");
    GET_SYMBOL(CCharacterMng::setShadowType, "_ZN13CCharacterMng13setShadowTypeEii");
    GET_SYMBOL(CCharacterMng::setTransparencyRate, "_ZN13CCharacterMng19setTransparencyRateEii");
    GET_SYMBOL(CCharacterMng::startMotion, "_ZN13CCharacterMng11startMotionEiibj");
    GET_SYMBOL(common::EfficacyDataConvection::Ctor, "_ZN6common22EfficacyDataConvectionC2Ev");
    GET_SYMBOL(common::EfficacyDataConvection::Dtor, "_ZN6common22EfficacyDataConvectionD2Ev");
    GET_SYMBOL(common::EfficacyDataConvection::getEfficacyData, "_ZN6common22EfficacyDataConvection15getEfficacyDataEi");
    GET_SYMBOL(common::EfficacyDataConvection::initialize, "_ZN6common22EfficacyDataConvection10initializeEv");
    GET_SYMBOL(common::EfficacyDataConvection::loadBELD, "_ZN6common22EfficacyDataConvection8loadBELDEv");
    GET_SYMBOL(common::EfficacyDataConvection::terminate, "_ZN6common22EfficacyDataConvection9terminateEv");
    GET_SYMBOL(common::EfficacyDataConvection::unloadBELD, "_ZN6common22EfficacyDataConvection10unloadBELDEv");
    GET_SYMBOL(CTextureDataMng::delData, "_ZN15CTextureDataMng7delDataEi");
    GET_SYMBOL(CTextureDataMng::end, "_ZN15CTextureDataMng3endEv");
    GET_SYMBOL(CTextureDataMng::getTex, "_ZN15CTextureDataMng6getTexEi");
    GET_SYMBOL(CTextureDataMng::init, "_ZN15CTextureDataMng4initEv");
    GET_SYMBOL(CTextureDataMng::initValue, "_ZN15CTextureDataMng9initValueEi");
    GET_SYMBOL(CTextureDataMng::releaseLnkTexVram, "_ZN15CTextureDataMng17releaseLnkTexVramEi");
    GET_SYMBOL(CTextureDataMng::searchDataIndex, "_ZN15CTextureDataMng15searchDataIndexEPKc");
    GET_SYMBOL(CTextureDataMng::searchNullIndex, "_ZN15CTextureDataMng15searchNullIndexEv");
    GET_SYMBOL(CTextureDataMng::setData, "_ZN15CTextureDataMng7setDataEPKcb");
    GET_SYMBOL(CTextureDataMng::setData2, "_ZN15CTextureDataMng8setData2EPKcS1_b");
    GET_SYMBOL(CTextureDataMng::setTextureData, "_ZN15CTextureDataMng14setTextureDataEPKcb");
    GET_SYMBOL(CTextureDataMng::setupLnkTexVram, "_ZN15CTextureDataMng15setupLnkTexVramEib");
    GET_SYMBOL(CTextureDataMng::useTexture, "_ZN15CTextureDataMng10useTextureEi");
    GET_SYMBOL(debug::CharaViewerPart::doInitialize, "_ZN5debug15CharaViewerPart12doInitializeEv");
    GET_SYMBOL(dgs::DGSMsdGetString, "_ZN3dgs15DGSMsdGetStringEjhPNS_6DGSMSDE");
    GET_SYMBOL(ds::CPad::repeat, "_ZN2ds4CPad6repeatEv");
    GET_SYMBOL(ds::CVram::releasePlttVramMng, "_ZN2ds5CVram18releasePlttVramMngEv");
    GET_SYMBOL(ds::CVram::releaseTexVramMng, "_ZN2ds5CVram17releaseTexVramMngEv");
    GET_SYMBOL(ds::CVram::setupPlttVramMng, "_ZN2ds5CVram16setupPlttVramMngEjjc");
    GET_SYMBOL(ds::CVram::setupTexVramMng, "_ZN2ds5CVram15setupTexVramMngEjjjc");
    GET_SYMBOL(ds::snd::dssndInitialize, "_ZN2ds3snd15dssndInitializeEPKNS0_11DSSoundDescE");
    GET_SYMBOL(ds::snd::dssndUnloadBGM1, "_ZN2ds3snd14dssndUnloadBGMEv");
    GET_SYMBOL(ds::snd::dssndUnloadBGM2, "_ZN2ds3snd14dssndUnloadBGMEi");
    GET_SYMBOL(ds::snd::dssndUnloadBGMAll, "_ZN2ds3snd17dssndUnloadBGMAllEv");
    GET_SYMBOL(ds::snd::dssndUnloadSE1, "_ZN2ds3snd13dssndUnloadSEEv");
    GET_SYMBOL(ds::snd::dssndUnloadSE2, "_ZN2ds3snd13dssndUnloadSEEi");
    GET_SYMBOL(ds::snd::dssndUnloadSEAll, "_ZN2ds3snd16dssndUnloadSEAllEv");
    GET_SYMBOL(ds::snd::dssndUpdate, "_ZN2ds3snd11dssndUpdateEv");
    GET_SYMBOL(ds::snd::BGMHandle::Ctor, "_ZN2ds3snd9BGMHandleC1Ev");
    GET_SYMBOL(ds::snd::BGMHandle::Dtor, "_ZN2ds3snd9BGMHandleD1Ev");
    GET_SYMBOL(ds::snd::BGMHandle::forceReleaseSequence, "_ZN2ds3snd9BGMHandle20forceReleaseSequenceEv");
    GET_SYMBOL(ds::snd::BGMHandle::getBGMEnable, "_ZN2ds3snd9BGMHandle12setBGMEnableEv");
    GET_SYMBOL(ds::snd::BGMHandle::IsPlaying, "_ZN2ds3snd9BGMHandle9IsPlayingEv");
    GET_SYMBOL(ds::snd::BGMHandle::MoveVolume, "_ZN2ds3snd9BGMHandle10MoveVolumeEii");
    GET_SYMBOL(ds::snd::BGMHandle::Pause, "_ZN2ds3snd9BGMHandle5PauseEc");
    GET_SYMBOL(ds::snd::BGMHandle::Play, "_ZN2ds3snd9BGMHandle4PlayEiiii");
    GET_SYMBOL(ds::snd::BGMHandle::PlayV, "_ZN2ds3snd9BGMHandle4PlayERKi");
    GET_SYMBOL(ds::snd::BGMHandle::seqNo, "_ZN2ds3snd9BGMHandle5seqNoEv");
    GET_SYMBOL(ds::snd::BGMHandle::setBGMEnable, "_ZN2ds3snd9BGMHandle12setBGMEnableEb");
    GET_SYMBOL(ds::snd::BGMHandle::setTempo, "_ZN2ds3snd9BGMHandle8setTempoEi");
    GET_SYMBOL(ds::snd::BGMHandle::SetVolume, "_ZN2ds3snd9BGMHandle9SetVolumeEi");
    GET_SYMBOL(ds::snd::BGMHandle::Stop, "_ZN2ds3snd9BGMHandle4StopEi");
    GET_SYMBOL(ds::snd::DSSoundHeap::dsshFinalize, "_ZN2ds3snd11DSSoundHeap12dsshFinalizeEv");
    GET_SYMBOL(ds::snd::SEHandle::Ctor, "_ZN2ds3snd8SEHandleC1Ev");
    GET_SYMBOL(ds::snd::SEHandle::Dtor, "_ZN2ds3snd8SEHandleD1Ev");
    GET_SYMBOL(ds::snd::SEHandle::IsPlaying, "_ZN2ds3snd8SEHandle9IsPlayingEv");
    GET_SYMBOL(ds::snd::SEHandle::MoveVolume, "_ZN2ds3snd8SEHandle9setVolumeEii");
    GET_SYMBOL(ds::snd::SEHandle::Play, "_ZN2ds3snd8SEHandle4PlayEiiii");
    GET_SYMBOL(ds::snd::SEHandle::PlayFadeIn, "_ZN2ds3snd8SEHandle10PlayFadeInEiiiii");
    GET_SYMBOL(ds::snd::SEHandle::setPan, "_ZN2ds3snd8SEHandle6setPanEti");
    GET_SYMBOL(ds::snd::SEHandle::setPanRange, "_ZN2ds3snd8SEHandle11setPanRangeEti");
    GET_SYMBOL(ds::snd::SEHandle::setPitch, "_ZN2ds3snd8SEHandle8setPitchEti");
    GET_SYMBOL(ds::snd::SEHandle::setTempo, "_ZN2ds3snd8SEHandle8setTempoEi");
    GET_SYMBOL(ds::snd::SEHandle::setVolume, "_ZN2ds3snd8SEHandle9setVolumeEi");
    GET_SYMBOL(ds::snd::SEHandle::stop, "_ZN2ds3snd8SEHandle4stopEi");
    GET_SYMBOL(ds::sys3d::CAnimation::ctor, "_ZN2ds5sys3d10CAnimationC1Ev");
    GET_SYMBOL(ds::sys3d::CAnimation::getFrameRate, "_ZN2ds5sys3d10CAnimation12getFrameRateEv");
    GET_SYMBOL(ds::sys3d::CAnimation::setFrameRate, "_ZN2ds5sys3d10CAnimation12setFrameRateEi");
    GET_SYMBOL(ds::sys3d::CAnimation::setup, "_ZN2ds5sys3d10CAnimation5setupEPvS2_jS2_");
    GET_SYMBOL(ds::sys3d::CCamera::setFOV, "_ZN2ds5sys3d7CCamera6setFOVEii");
    GET_SYMBOL(ds::sys3d::CModelTexture::bindMdl, "_ZN2ds5sys3d13CModelTexture7bindMdlEP12NNSG3dResMdl");
    GET_SYMBOL(ds::sys3d::CModelTexture::bindMdlSet, "_ZN2ds5sys3d13CModelTexture10bindMdlSetEP15NNSG3dResMdlSet");
    GET_SYMBOL(ds::sys3d::CModelTexture::bindMdlToPltt, "_ZN2ds5sys3d13CModelTexture13bindMdlToPlttEP12NNSG3dResMdl");
    GET_SYMBOL(ds::sys3d::CModelTexture::bindMdlToPlttByName, "_ZN2ds5sys3d13CModelTexture19bindMdlToPlttByNameEP12NNSG3dResMdlPKc");
    GET_SYMBOL(ds::sys3d::CModelTexture::bindMdlToTex, "_ZN2ds5sys3d13CModelTexture12bindMdlToTexEP12NNSG3dResMdl");
    GET_SYMBOL(ds::sys3d::CModelTexture::bindMdlToTexByName, "_ZN2ds5sys3d13CModelTexture18bindMdlToTexByNameEP12NNSG3dResMdlPKc");
    GET_SYMBOL(ds::sys3d::CModelTexture::bindTexPlt, "_ZN2ds5sys3d13CModelTexture10bindTexPltEv");
    GET_SYMBOL(ds::sys3d::CModelTexture::cleanup, "_ZN2ds5sys3d13CModelTexture7cleanupEv");
    GET_SYMBOL(ds::sys3d::CModelTexture::clearValue, "_ZN2ds5sys3d13CModelTexture10clearValueEv");
    GET_SYMBOL(ds::sys3d::CModelTexture::Ctor, "_ZN2ds5sys3d13CModelTextureC1Ev");
    GET_SYMBOL(ds::sys3d::CModelTexture::Dtor, "_ZN2ds5sys3d13CModelTextureD1Ev");
    GET_SYMBOL(ds::sys3d::CModelTexture::isModelTexture, "_ZN2ds5sys3d13CModelTexture14isModelTextureEPv");
    GET_SYMBOL(ds::sys3d::CModelTexture::releaseMdl, "_ZN2ds5sys3d13CModelTexture10releaseMdlEP12NNSG3dResMdl");
    GET_SYMBOL(ds::sys3d::CModelTexture::releaseMdlSet, "_ZN2ds5sys3d13CModelTexture13releaseMdlSetEP15NNSG3dResMdlSet");
    GET_SYMBOL(ds::sys3d::CModelTexture::releaseMdlToPltt, "_ZN2ds5sys3d13CModelTexture16releaseMdlToPlttEP12NNSG3dResMdl");
    GET_SYMBOL(ds::sys3d::CModelTexture::releaseMdlToPlttByName, "_ZN2ds5sys3d13CModelTexture22releaseMdlToPlttByNameEP12NNSG3dResMdlPKc");
    GET_SYMBOL(ds::sys3d::CModelTexture::releaseMdlToTex, "_ZN2ds5sys3d13CModelTexture15releaseMdlToTexEP12NNSG3dResMdl");
    GET_SYMBOL(ds::sys3d::CModelTexture::releaseMdlToTexByName, "_ZN2ds5sys3d13CModelTexture21releaseMdlToTexByNameEP12NNSG3dResMdlPKc");
    GET_SYMBOL(ds::sys3d::CModelTexture::releaseResource, "_ZN2ds5sys3d13CModelTexture15releaseResourceEv");
    GET_SYMBOL(ds::sys3d::CModelTexture::reqReleaseResource, "_ZN2ds5sys3d13CModelTexture18reqReleaseResourceEv");
    GET_SYMBOL(ds::sys3d::CModelTexture::setup, "_ZN2ds5sys3d13CModelTexture5setupEPvb");
    GET_SYMBOL(ds::sys3d::CModelTexture::tdlhCompletion, "_ZN2ds5sys3d13CModelTexture14tdlhCompletionEi");
    GET_SYMBOL(ds::sys3d::CMotSet::getFrameRate, "_ZN2ds5sys3d7CMotSet12getFrameRateEv");
    GET_SYMBOL(ds::sys3d::CMotSet::setFrameRate, "_ZN2ds5sys3d7CMotSet12setFrameRateEi");
    GET_SYMBOL(egs::GilbartInitialize, "_ZN3egs17GilbartInitializeEbb");
    GET_SYMBOL(egs::GilbartIsEndOfPlayVoice, "_ZN3egs23GilbartIsEndOfPlayVoiceEi");
    GET_SYMBOL(egs::GilbartIsPlaying, "_ZN3egs16GilbartIsPlayingEi");
    GET_SYMBOL(egs::GilbartPauseVoice, "_ZN3egs17GilbartPauseVoiceEib");
    GET_SYMBOL(egs::GilbartPlayVoice, "_ZN3egs16GilbartPlayVoiceEPKci");
    GET_SYMBOL(egs::GilbartProcess, "_ZN3egs14GilbartProcessEPv");
    GET_SYMBOL(egs::GilbartSetVolume, "_ZN3egs16GilbartSetVolumeEif");
    GET_SYMBOL(egs::GilbartStatus, "_ZN3egs13GilbartStatusEi");
    GET_SYMBOL(egs::GilbartStopVoice, "_ZN3egs16GilbartStopVoiceEi");
    GET_SYMBOL(egs::GilbartTerminate, "_ZN3egs16GilbartTerminateEv");
    GET_SYMBOL(evt::EventCamera::startCameraMotion, "_ZN3evt11EventCamera17startCameraMotionEjjjb");
    GET_SYMBOL(FlagManager::Ctor, "_ZN11FlagManagerC1Ev");
    GET_SYMBOL(FlagManager::Dtor, "_ZN11FlagManagerD1Ev");
    GET_SYMBOL(FlagManager::get, "_ZN11FlagManager3getEjj");
    GET_SYMBOL(FlagManager::reset, "_ZN11FlagManager5resetEjj");
    GET_SYMBOL(FlagManager::reverse, "_ZN11FlagManager7reverseEjj");
    GET_SYMBOL(FlagManager::set, "_ZN11FlagManager3setEjj");
    GET_SYMBOL(FlagManager::singleton, "_ZN11FlagManager9singletonEv");
    GET_SYMBOL(Font::initFont, "_ZN4Font8initFontEv");
    GET_SYMBOL(itm::EquipParameter::canEquip, "_ZN3itm14EquipParameter8canEquipEN2pl12PLAYER_TYPESE");
    GET_SYMBOL(itm::ItemManager::consumptionParameter, "_ZN3itm11ItemManager20consumptionParameterEs");
    GET_SYMBOL(itm::ItemManager::equipParameter, "_ZN3itm11ItemManager14equipParameterEs");
    GET_SYMBOL(itm::ItemManager::free, "_ZN3itm11ItemManager4freeEv");
    GET_SYMBOL(itm::ItemManager::importantParameter, "_ZN3itm11ItemManager18importantParameterEs");
    GET_SYMBOL(itm::ItemManager::itemCategory, "_ZN3itm11ItemManager12itemCategoryEs");
    GET_SYMBOL(itm::ItemManager::itemParameter, "_ZN3itm11ItemManager13itemParameterEs");
    GET_SYMBOL(itm::ItemManager::load, "_ZN3itm11ItemManager4loadEv");
    GET_SYMBOL(itm::ItemManager::protectionParameter, "_ZN3itm11ItemManager19protectionParameterEs");
    GET_SYMBOL(itm::ItemManager::weaponParameter, "_ZN3itm11ItemManager15weaponParameterEs");
    GET_SYMBOL(itm::PossessionItemManager::eraseAllImportantItem, "_ZN3itm21PossessionItemManager21eraseAllImportantItemEv");
    GET_SYMBOL(itm::PossessionItemManager::eraseAllNormalItem, "_ZN3itm21PossessionItemManager18eraseAllNormalItemEv");
    GET_SYMBOL(itm::PossessionItemManager::eraseItem, "_ZN3itm21PossessionItemManager9eraseItemEsi");
    GET_SYMBOL(itm::PossessionItemManager::importantItem, "_ZN3itm21PossessionItemManager13importantItemEi");
    GET_SYMBOL(itm::PossessionItemManager::importantItemNum, "_ZN3itm21PossessionItemManager16importantItemNumEv");
    GET_SYMBOL(itm::PossessionItemManager::initialize, "_ZN3itm21PossessionItemManager10initializeEv");
    GET_SYMBOL(itm::PossessionItemManager::itemAllNum, "_ZN3itm21PossessionItemManager10itemAllNumEv");
    GET_SYMBOL(itm::PossessionItemManager::normalItem, "_ZN3itm21PossessionItemManager10normalItemEi");
    GET_SYMBOL(itm::PossessionItemManager::normalItemNum, "_ZN3itm21PossessionItemManager13normalItemNumEv");
    GET_SYMBOL(itm::PossessionItemManager::reserveCancel, "_ZN3itm21PossessionItemManager13reserveCancelEv");
    GET_SYMBOL(itm::PossessionItemManager::resetImportantItemId, "_ZN3itm21PossessionItemManager20resetImportantItemIdEv");
    GET_SYMBOL(itm::PossessionItemManager::resetItemId, "_ZN3itm21PossessionItemManager11resetItemIdEv");
    GET_SYMBOL(itm::PossessionItemManager::searchImportantItem, "_ZN3itm21PossessionItemManager19searchImportantItemEs");
    GET_SYMBOL(itm::PossessionItemManager::searchNormalItem, "_ZN3itm21PossessionItemManager16searchNormalItemEs");
    GET_SYMBOL(itm::PossessionItemManager::storeImportantItem, "_ZN3itm21PossessionItemManager18storeImportantItemEsi");
    GET_SYMBOL(itm::PossessionItemManager::storeItem, "_ZN3itm21PossessionItemManager9storeItemEsi");
    GET_SYMBOL(itm::PossessionItemManager::swapItem, "_ZN3itm21PossessionItemManager8swapItemEss");
    GET_SYMBOL(map2d::NaviMap::MapOff, "_ZN5map2d7NaviMap6MapOffEv");
    GET_SYMBOL(map2d::NaviMap::MapOn, "_ZN5map2d7NaviMap5MapOnEv");
    GET_SYMBOL(map2d::NaviMap::NaviMapDrawOff, "_ZN5map2d7NaviMap14NaviMapDrawOffEv");
    GET_SYMBOL(map2d::NaviMap::setAlpha, "_ZN5map2d7NaviMap8setAlphaEi");
    GET_SYMBOL(menu::playSECommon, "_ZN4menu12playSECommonEii");
    GET_SYMBOL(mon::MonsterManager::acceptMonsterManiaData, "_ZN3mon14MonsterManager22acceptMonsterManiaDataERNS_19MonsterManiaManagerE");
    GET_SYMBOL(mon::MonsterManager::actionCondition, "_ZN3mon14MonsterManager15actionConditionEi");
    GET_SYMBOL(mon::MonsterManager::ai, "_ZN3mon14MonsterManager2aiEi");
    GET_SYMBOL(mon::MonsterManager::counter, "_ZN3mon14MonsterManager7counterEi");
    GET_SYMBOL(mon::MonsterManager::dropItem, "_ZN3mon14MonsterManager8dropItemEi");
    GET_SYMBOL(mon::MonsterManager::effectsInfo, "_ZN3mon14MonsterManager11effectsInfoEN6common10ABILITY_IDEs");
    GET_SYMBOL(mon::MonsterManager::free, "_ZN3mon14MonsterManager4freeEv");
    GET_SYMBOL(mon::MonsterManager::load, "_ZN3mon14MonsterManager4loadEv");
    GET_SYMBOL(mon::MonsterManager::monsterManiaManager, "_ZN3mon14MonsterManager19monsterManiaManagerEv");
    GET_SYMBOL(mon::MonsterManager::monsterParameter, "_ZN3mon14MonsterManager16monsterParameterEi");
    GET_SYMBOL(mon::MonsterManager::normalAttack, "_ZN3mon14MonsterManager12normalAttackEi");
    GET_SYMBOL(mon::MonsterManager::octmanmosLegInfo, "_ZN3mon14MonsterManager16octmanmosLegInfoEhh");
    GET_SYMBOL(mon::MonsterManager::offset, "_ZN3mon14MonsterManager6offsetEi");
    GET_SYMBOL(mon::MonsterManager::sendMonsterManiaData, "_ZN3mon14MonsterManager20sendMonsterManiaDataERNS_19MonsterManiaManagerE");
    GET_SYMBOL(mon::MonsterManager::setMonsterIdForMonsterManaia, "_ZN3mon14MonsterManager28setMonsterIdForMonsterManaiaEv");
    GET_SYMBOL(mon::MonsterManager::turnAction, "_ZN3mon14MonsterManager10turnActionEi");
    GET_SYMBOL(mon::MonsterManiaManager::clearMonsterMania, "_ZN3mon19MonsterManiaManager17clearMonsterManiaEv");
    GET_SYMBOL(mon::MonsterManiaManager::kill, "_ZN3mon19MonsterManiaManager4killEs");
    GET_SYMBOL(mon::MonsterManiaManager::monsterMania, "_ZN3mon19MonsterManiaManager12monsterManiaEi");
    GET_SYMBOL(mon::MonsterManiaManager::onEncount, "_ZN3mon19MonsterManiaManager9onEncountEs");
    GET_SYMBOL(mon::MonsterManiaManager::onLibrary, "_ZN3mon19MonsterManiaManager9onLibraryEs");
    GET_SYMBOL(mon::MonsterManiaManager::setMonsterManiaForMonsterID, "_ZN3mon19MonsterManiaManager27setMonsterManiaForMonsterIDERNS_12MonsterManiaE");
    GET_SYMBOL(mr::getCompleteRate, "_ZN2mr15setCompleteRateEv");
    GET_SYMBOL(mr::MonsterRefDataManager::Ctor, "_ZN2mr21MonsterRefDataManagerC1Ev");
    GET_SYMBOL(mr::MonsterRefDataManager::Dtor, "_ZN2mr21MonsterRefDataManagerD1Ev");
    GET_SYMBOL(mr::MonsterRefDataManager::free, "_ZN2mr21MonsterRefDataManager4freeEv");
    GET_SYMBOL(mr::MonsterRefDataManager::load, "_ZN2mr21MonsterRefDataManager4loadEv");
    GET_SYMBOL(mr::MonsterRefDataManager::monsterReference, "_ZN2mr21MonsterRefDataManager16monsterReferenceEi");
    GET_SYMBOL(mr::MonsterRefDataManager::monsterReferenceFromIndex, "_ZN2mr21MonsterRefDataManager25monsterReferenceFromIndexEi");
    GET_SYMBOL(pl::LearningAbilityManager::clear, "_ZN2pl22LearningAbilityManager5clearENS0_22LEARNING_ABILITY_TYPESE");
    GET_SYMBOL(pl::LearningAbilityManager::forget, "_ZN2pl22LearningAbilityManager6forgetEN6common10ABILITY_IDE");
    GET_SYMBOL(pl::LearningAbilityManager::initialize, "_ZN2pl22LearningAbilityManager10initializeERNS_30LearningAbilityManagerContentsE");
    GET_SYMBOL(pl::LearningAbilityManager::isLearning, "_ZN2pl22LearningAbilityManager10isLearningEN6common10ABILITY_IDE");
    GET_SYMBOL(pl::LearningAbilityManager::isMagicTypesAbility, "_ZN2pl22LearningAbilityManager19isMagicTypesAbilityEN6common10ABILITY_IDE");
    GET_SYMBOL(pl::LearningAbilityManager::isOn, "_ZN2pl22LearningAbilityManager4isOnENS0_22LEARNING_ABILITY_TYPESEi");
    GET_SYMBOL(pl::LearningAbilityManager::learn, "_ZN2pl22LearningAbilityManager5learnEN6common10ABILITY_IDE");
    GET_SYMBOL(pl::LearningAbilityManager::learnForDebug, "_ZN2pl22LearningAbilityManager13learnForDebugEN6common10ABILITY_IDE");
    GET_SYMBOL(pl::LearningAbilityManager::learningMagicTypesNumber, "_ZN2pl22LearningAbilityManager24learningMagicTypesNumberEv");
    GET_SYMBOL(pl::LearningAbilityManager::off, "_ZN2pl22LearningAbilityManager3offENS0_22LEARNING_ABILITY_TYPESEi");
    GET_SYMBOL(pl::LearningAbilityManager::on, "_ZN2pl22LearningAbilityManager2onENS0_22LEARNING_ABILITY_TYPESEi");
    GET_SYMBOL(pl::LearningAbilityManager::setContents, "_ZN2pl22LearningAbilityManager11setContentsERNS_30LearningAbilityManagerContentsE");
    GET_SYMBOL(pl::Player::abilityBouns, "_ZN2pl6Player12abilityBounsEv");
    GET_SYMBOL(pl::Player::addEquipmentBonus, "_ZN2pl6Player17addEquipmentBonusERN2ys13BodyParameterEi");
    GET_SYMBOL(pl::Player::addMagicDefense, "_ZN2pl6Player15addMagicDefenseERN2ys21MagicDefenseParameterEi");
    GET_SYMBOL(pl::Player::addPhysicsDefense_ib, "_ZN2pl6Player17addPhysicsDefenseERN2ys23PhysicsDefenseParameterEib");
    GET_SYMBOL(pl::Player::addPhysicsDefense_Pb, "_ZN2pl6Player17addPhysicsDefenseERN2ys23PhysicsDefenseParameterEPN3itm19ProtectionParameterEb");
    GET_SYMBOL(pl::Player::adjustAbility, "_ZN2pl6Player13adjustAbilityEv");
    GET_SYMBOL(pl::Player::attachEquipmentSymbol, "_ZN2pl6Player21attachEquipmentSymbolEb");
    GET_SYMBOL(pl::Player::attachEquipmentSymbolOne, "_ZN2pl6Player24attachEquipmentSymbolOneENS_9HAND_TYPEEb");
    GET_SYMBOL(pl::Player::avoidance, "_ZN2pl6Player9avoidanceEv");
    GET_SYMBOL(pl::Player::bodyAndBonus, "_ZN2pl6Player12bodyAndBonusEv");
    GET_SYMBOL(pl::Player::bodyAndBonus_BP, "_ZN2pl6Player12bodyAndBonusERN2ys13BodyParameterEsssss");
    GET_SYMBOL(pl::Player::calcBonus, "_ZN2pl6Player9calcBonusEv");
    GET_SYMBOL(pl::Player::calcHpColor, "_ZN2pl6Player11calcHpColorEii");
    GET_SYMBOL(pl::Player::calcMagicDefense, "_ZN2pl6Player16calcMagicDefenseEv");
    GET_SYMBOL(pl::Player::calcPhysicsDefense, "_ZN2pl6Player18calcPhysicsDefenseEv");
    GET_SYMBOL(pl::Player::canEquip, "_ZN2pl6Player8canEquipEsNS_9HAND_TYPEE");
    GET_SYMBOL(pl::Player::canEquipArrow, "_ZN2pl6Player13canEquipArrowEiPN3itm15WeaponParameterE");
    GET_SYMBOL(pl::Player::canEquipBow, "_ZN2pl6Player11canEquipBowEiPN3itm15WeaponParameterEb");
    GET_SYMBOL(pl::Player::canEquipHarp, "_ZN2pl6Player12canEquipHarpEiPN3itm15WeaponParameterEb");
    GET_SYMBOL(pl::Player::canEquipWeapon, "_ZN2pl6Player14canEquipWeaponEiPN3itm15WeaponParameterE");
    GET_SYMBOL(pl::Player::canGivenExp, "_ZN2pl6Player11canGivenExpEv");
    GET_SYMBOL(pl::Player::canWinningDirection, "_ZN2pl6Player19canWinningDirectionEv");
    GET_SYMBOL(pl::Player::changeStonePalette, "_ZN2pl6Player18changeStonePaletteEb");
    GET_SYMBOL(pl::Player::changeStonePaletteForEvent, "_ZN2pl6Player26changeStonePaletteForEventEb");
    GET_SYMBOL(pl::Player::checkHpColor, "_ZN2pl6Player12checkHpColorEv");
    GET_SYMBOL(pl::Player::clearCommand, "_ZN2pl6Player12clearCommandEv");
    GET_SYMBOL(pl::Player::condition, "_ZN2pl6Player9conditionEv");
    GET_SYMBOL(pl::Player::Ctor, "_ZN2pl6PlayerC2Ev");
    GET_SYMBOL(pl::Player::decantLevel, "_ZN2pl6Player11decantLevelEv");
    GET_SYMBOL(pl::Player::defaultMaxHp, "_ZN2pl6Player12defaultMaxHpEv");
    GET_SYMBOL(pl::Player::defaultMaxMp, "_ZN2pl6Player12defaultMaxMpEv");
    GET_SYMBOL(pl::Player::deftness, "_ZN2pl6Player8deftnessEv");
    GET_SYMBOL(pl::Player::difference, "_ZN2pl6Player10differenceEii");
    GET_SYMBOL(pl::Player::doEquip, "_ZN2pl6Player7doEquipEisb");
    GET_SYMBOL(pl::Player::Dtor, "_ZN2pl6PlayerD2Ev");
    GET_SYMBOL(pl::Player::equipmentAttach, "_ZN2pl6Player15equipmentAttachENS_9HAND_TYPEE");
    GET_SYMBOL(pl::Player::equipmentBounsHP, "_ZN2pl6Player16equipmentBounsHPEv");
    GET_SYMBOL(pl::Player::equipmentSymbolVisibility, "_ZN2pl6Player25equipmentSymbolVisibilityEb");
    GET_SYMBOL(pl::Player::equipMenuParameter, "_ZN2pl6Player18equipMenuParameterEsssss");
    GET_SYMBOL(pl::Player::equipParameter, "_ZN2pl6Player14equipParameterEv");
    GET_SYMBOL(pl::Player::exp, "_ZN2pl6Player3expEv");
    GET_SYMBOL(pl::Player::fine, "_ZN2pl6Player4fineEv");
    GET_SYMBOL(pl::Player::forgetAbility_AI, "_ZN2pl6Player13forgetAbilityEN6common10ABILITY_IDE");
    GET_SYMBOL(pl::Player::forgetAbility_i, "_ZN2pl6Player13forgetAbilityEi");
    GET_SYMBOL(pl::Player::forgetAllAbilityForDebug, "_ZN2pl6Player24forgetAllAbilityForDebugEv");
    GET_SYMBOL(pl::Player::forgetAllBlackMagicForDebug, "_ZN2pl6Player27forgetAllBlackMagicForDebugEv");
    GET_SYMBOL(pl::Player::forgetAllNinjutsuForDebug, "_ZN2pl6Player25forgetAllNinjutsuForDebugEv");
    GET_SYMBOL(pl::Player::forgetAllSongForDebug, "_ZN2pl6Player21forgetAllSongForDebugEv");
    GET_SYMBOL(pl::Player::forgetAllSummonForDebug, "_ZN2pl6Player23forgetAllSummonForDebugEv");
    GET_SYMBOL(pl::Player::forgetAllWhiteMagicForDebug, "_ZN2pl6Player27forgetAllWhiteMagicForDebugEv");
    GET_SYMBOL(pl::Player::forgetLearnedMagicByEvent, "_ZN2pl6Player25forgetLearnedMagicByEventEv");
    GET_SYMBOL(pl::Player::growParameter, "_ZN2pl6Player13growParameterEh");
    GET_SYMBOL(pl::Player::hp, "_ZN2pl6Player2hpEv");
    GET_SYMBOL(pl::Player::initialize, "_ZN2pl6Player10initializeENS_12PLAYER_TYPESE");
    GET_SYMBOL(pl::Player::initializeCommand, "_ZN2pl6Player17initializeCommandEv");
    GET_SYMBOL(pl::Player::initializeDefaultCommand, "_ZN2pl6Player24initializeDefaultCommandEv");
    GET_SYMBOL(pl::Player::initializeName, "_ZN2pl6Player14initializeNameEv");
    GET_SYMBOL(pl::Player::isCanEquipProtection, "_ZN2pl6Player20isCanEquipProtectionEiPN3itm19ProtectionParameterE");
    GET_SYMBOL(pl::Player::isCommand, "_ZN2pl6Player9isCommandEN6common10ABILITY_IDE");
    GET_SYMBOL(pl::Player::isEquipable, "_ZN2pl6Player11isEquipableENS_12EQUIP_POINTSEs");
    GET_SYMBOL(pl::Player::isEquipedItemOnAllPoints, "_ZN2pl6Player24isEquipedItemOnAllPointsEs");
    GET_SYMBOL(pl::Player::isEquipedItemOnPoint, "_ZN2pl6Player20isEquipedItemOnPointEis");
    GET_SYMBOL(pl::Player::isEquipItem, "_ZN2pl6Player11isEquipItemEPN3itm14EquipParameterE");
    GET_SYMBOL(pl::Player::isEquipMetal, "_ZN2pl6Player12isEquipMetalEv");
    GET_SYMBOL(pl::Player::isEquippedBow, "_ZN2pl6Player13isEquippedBowEv");
    GET_SYMBOL(pl::Player::isFinishAttack, "_ZN2pl6Player14isFinishAttackEv");
    GET_SYMBOL(pl::Player::isHand, "_ZN2pl6Player6isHandEib");
    GET_SYMBOL(pl::Player::isHandCheck, "_ZN2pl6Player11isHandCheckEiPN3itm15WeaponParameterEPNS1_19ProtectionParameterEbb");
    GET_SYMBOL(pl::Player::isHealing, "_ZN2pl6Player9isHealingEv");
    GET_SYMBOL(pl::Player::isKnowledgeInCommand, "_ZN2pl6Player20isKnowledgeInCommandEv");
    GET_SYMBOL(pl::Player::isUseMagic_AI, "_ZN2pl6Player10isUseMagicEN6common10ABILITY_IDEib");
    GET_SYMBOL(pl::Player::isUseMagic_BM, "_ZN2pl6Player10isUseMagicEPN6common19BabilMagicParameterEib");
    GET_SYMBOL(pl::Player::isUseMagicCharacter, "_ZN2pl6Player19isUseMagicCharacterEv");
    GET_SYMBOL(pl::Player::learnAbility_AI, "_ZN2pl6Player12learnAbilityEN6common10ABILITY_IDE");
    GET_SYMBOL(pl::Player::learnAbility_ii, "_ZN2pl6Player12learnAbilityEii");
    GET_SYMBOL(pl::Player::learnAbilityForDebug, "_ZN2pl6Player20learnAbilityForDebugEN6common10ABILITY_IDE");
    GET_SYMBOL(pl::Player::learnAllAbilityForDebug, "_ZN2pl6Player23learnAllAbilityForDebugEv");
    GET_SYMBOL(pl::Player::learnAllBlackMagicForDebug, "_ZN2pl6Player26learnAllBlackMagicForDebugEv");
    GET_SYMBOL(pl::Player::learnAllNinjutsuForDebug, "_ZN2pl6Player24learnAllNinjutsuForDebugEv");
    GET_SYMBOL(pl::Player::learnAllSongForDebug, "_ZN2pl6Player20learnAllSongForDebugEv");
    GET_SYMBOL(pl::Player::learnAllSummonForDebug, "_ZN2pl6Player22learnAllSummonForDebugEv");
    GET_SYMBOL(pl::Player::learnAllWhiteMagicForDebug, "_ZN2pl6Player26learnAllWhiteMagicForDebugEv");
    GET_SYMBOL(pl::Player::learningAbility, "_ZN2pl6Player15learningAbilityEv");
    GET_SYMBOL(pl::Player::level, "_ZN2pl6Player5levelEv");
    GET_SYMBOL(pl::Player::levelDown, "_ZN2pl6Player9levelDownEi");
    GET_SYMBOL(pl::Player::levelUp, "_ZN2pl6Player7levelUpEi");
    GET_SYMBOL(pl::Player::listupCommand, "_ZN2pl6Player13listupCommandERNS_17SummonAbilityListE");
    GET_SYMBOL(pl::Player::listupCommandMagic, "_ZN2pl6Player18listupCommandMagicERNS_17SummonAbilityListENS1_5TYPESE");
    GET_SYMBOL(pl::Player::listupCommandNormal, "_ZN2pl6Player19listupCommandNormalERNS_17SummonAbilityListE");
    GET_SYMBOL(pl::Player::magicDefense, "_ZN2pl6Player12magicDefenseERN2ys21MagicDefenseParameterEsssss");
    GET_SYMBOL(pl::Player::magicDefensePower, "_ZN2pl6Player17magicDefensePowerEv");
    GET_SYMBOL(pl::Player::mp, "_ZN2pl6Player2mpEv");
    GET_SYMBOL(pl::Player::physicsAttack, "_ZN2pl6Player13physicsAttackERN2ys22PhysicsAttackParameterEsssss");
    GET_SYMBOL(pl::Player::physicsDefense, "_ZN2pl6Player14physicsDefenseERN2ys23PhysicsDefenseParameterEsssss");
    GET_SYMBOL(pl::Player::playerAbilityManager, "_ZN2pl6Player20playerAbilityManagerEv");
    GET_SYMBOL(pl::Player::recoverHPandMP, "_ZN2pl6Player14recoverHPandMPEv");
    GET_SYMBOL(pl::Player::releaseEquipItem, "_ZN2pl6Player16releaseEquipItemEi");
    GET_SYMBOL(pl::Player::removeEquipmentSymbol, "_ZN2pl6Player21removeEquipmentSymbolEv");
    GET_SYMBOL(pl::Player::removeEquipmentSymbolOne, "_ZN2pl6Player24removeEquipmentSymbolOneENS_9HAND_TYPEE");
    GET_SYMBOL(pl::Player::saveParameter, "_ZN2pl6Player13saveParameterEv");
    GET_SYMBOL(pl::Player::setExp, "_ZN2pl6Player6setExpEh");
    GET_SYMBOL(pl::Player::setHp, "_ZN2pl6Player5setHpEh");
    GET_SYMBOL(pl::Player::setParameter, "_ZN2pl6Player12setParameterEhh");
    GET_SYMBOL(pl::Player::setPhysicsAttack, "_ZN2pl6Player16setPhysicsAttackEv");
    GET_SYMBOL(pl::Player::spendMp, "_ZN2pl6Player7spendMpEPN6common19BabilMagicParameterE");
    GET_SYMBOL(pl::Player::stonePaletteName, "_ZN2pl6Player16stonePaletteNameEPc");
    GET_SYMBOL(pl::Player::updateCondition, "_ZN2pl6Player15updateConditionEv");
    GET_SYMBOL(pl::Player::updateEquipmentSymbol, "_ZN2pl6Player21updateEquipmentSymbolEv");
    GET_SYMBOL(pl::Player::updateParameter, "_ZN2pl6Player15updateParameterEv");
    GET_SYMBOL(pl::Player::useApple, "_ZN2pl6Player8useAppleEb");
    GET_SYMBOL(pl::Player::useSomaDrop, "_ZN2pl6Player11useSomaDropEv");
    GET_SYMBOL(pl::PlayerParty::abilityBouns, "_ZN2pl11PlayerParty12abilityBounsEN6common10ABILITY_IDE");
    GET_SYMBOL(pl::PlayerParty::abilityList, "_ZN2pl11PlayerParty11abilityListEi");
    GET_SYMBOL(pl::PlayerParty::addItem, "_ZN2pl11PlayerParty7addItemEii");
    GET_SYMBOL(pl::PlayerParty::addMember, "_ZN2pl11PlayerParty9addMemberENS_12PLAYER_TYPESEi");
    GET_SYMBOL(pl::PlayerParty::aliveNumber, "_ZN2pl11PlayerParty11aliveNumberEv");
    GET_SYMBOL(pl::PlayerParty::averageLevel, "_ZN2pl11PlayerParty12averageLevelENS_12PLAYER_TYPESE");
    GET_SYMBOL(pl::PlayerParty::changeFormation, "_ZN2pl11PlayerParty15changeFormationEv");
    GET_SYMBOL(pl::PlayerParty::changeMember, "_ZN2pl11PlayerParty12changeMemberENS_12PLAYER_TYPESES1_");
    GET_SYMBOL(pl::PlayerParty::changeMemberForOrder, "_ZN2pl11PlayerParty20changeMemberForOrderEhh");
    GET_SYMBOL(pl::PlayerParty::changeStonePalette, "_ZN2pl11PlayerParty18changeStonePaletteEb");
    GET_SYMBOL(pl::PlayerParty::changeStonePaletteForEvent, "_ZN2pl11PlayerParty26changeStonePaletteForEventEb");
    GET_SYMBOL(pl::PlayerParty::clearBattleCommand, "_ZN2pl11PlayerParty18clearBattleCommandEv");
    GET_SYMBOL(pl::PlayerParty::clearBattleCommandPlayer, "_ZN2pl11PlayerParty24clearBattleCommandPlayerEi");
    GET_SYMBOL(pl::PlayerParty::clearBattleCondition, "_ZN2pl11PlayerParty20clearBattleConditionEv");
    GET_SYMBOL(pl::PlayerParty::Ctor, "_ZN2pl11PlayerPartyC2Ev");
    GET_SYMBOL(pl::PlayerParty::Dtor, "_ZN2pl11PlayerPartyD2Ev");
    GET_SYMBOL(pl::PlayerParty::fineAll, "_ZN2pl11PlayerParty7fineAllEv");
    GET_SYMBOL(pl::PlayerParty::formation, "_ZN2pl11PlayerParty9formationEh");
    GET_SYMBOL(pl::PlayerParty::free, "_ZN2pl11PlayerParty4freeEv");
    GET_SYMBOL(pl::PlayerParty::initForNewgame, "_ZN2pl11PlayerParty14initForNewgameEb");
    GET_SYMBOL(pl::PlayerParty::initialize, "_ZN2pl11PlayerParty10initializeEv");
    GET_SYMBOL(pl::PlayerParty::initializeName, "_ZN2pl11PlayerParty14initializeNameEv");
    GET_SYMBOL(pl::PlayerParty::isCommand, "_ZN2pl11PlayerParty9isCommandEN6common10ABILITY_IDE");
    GET_SYMBOL(pl::PlayerParty::isEnableMember, "_ZN2pl11PlayerParty14isEnableMemberEv");
    GET_SYMBOL(pl::PlayerParty::isFrogAll, "_ZN2pl11PlayerParty9isFrogAllEv");
    GET_SYMBOL(pl::PlayerParty::isJoinedParty, "_ZN2pl11PlayerParty13isJoinedPartyENS_12PLAYER_TYPESE");
    GET_SYMBOL(pl::PlayerParty::isLearnByLevelUp, "_ZN2pl11PlayerParty16isLearnByLevelUpENS_12PLAYER_TYPESEN6common10ABILITY_IDE");
    GET_SYMBOL(pl::PlayerParty::isLilliputAll, "_ZN2pl11PlayerParty13isLilliputAllEv");
    GET_SYMBOL(pl::PlayerParty::isPartyFull, "_ZN2pl11PlayerParty11isPartyFullEv");
    GET_SYMBOL(pl::PlayerParty::layoutSceneParameter, "_ZN2pl11PlayerParty20layoutSceneParameterEi");
    GET_SYMBOL(pl::PlayerParty::learningAbility, "_ZN2pl11PlayerParty15learningAbilityENS_12PLAYER_TYPESEi");
    GET_SYMBOL(pl::PlayerParty::levelParameter, "_ZN2pl11PlayerParty14levelParameterENS_12PLAYER_TYPESEc");
    GET_SYMBOL(pl::PlayerParty::listupCommand, "_ZN2pl11PlayerParty13listupCommandERNS_17SummonAbilityListE");
    GET_SYMBOL(pl::PlayerParty::load, "_ZN2pl11PlayerParty4loadEv");
    GET_SYMBOL(pl::PlayerParty::loadComposition, "_ZN2pl11PlayerParty15loadCompositionEv");
    GET_SYMBOL(pl::PlayerParty::member, "_ZN2pl11PlayerParty6memberENS_12PLAYER_TYPESE");
    GET_SYMBOL(pl::PlayerParty::memberForOrder, "_ZN2pl11PlayerParty14memberForOrderEh");
    GET_SYMBOL(pl::PlayerParty::memberOrder, "_ZN2pl11PlayerParty11memberOrderENS_12PLAYER_TYPESE");
    GET_SYMBOL(pl::PlayerParty::normalAttack, "_ZN2pl11PlayerParty12normalAttackEi");
    GET_SYMBOL(pl::PlayerParty::normalMagic, "_ZN2pl11PlayerParty11normalMagicEi");
    GET_SYMBOL(pl::PlayerParty::partyMemberEnableNumber, "_ZN2pl11PlayerParty23partyMemberEnableNumberEv");
    GET_SYMBOL(pl::PlayerParty::player, "_ZN2pl11PlayerParty6playerENS_12PLAYER_TYPESE");
    GET_SYMBOL(pl::PlayerParty::releaseMember, "_ZN2pl11PlayerParty13releaseMemberENS_12PLAYER_TYPESE");
    GET_SYMBOL(pl::PlayerParty::saveComposition, "_ZN2pl11PlayerParty15saveCompositionEv");
    GET_SYMBOL(pl::PlayerParty::setFormation, "_ZN2pl11PlayerParty12setFormationENS_21PARTY_FORMATION_TYPESE");
    GET_SYMBOL(pl::PlayerParty::setMemberForOrder, "_ZN2pl11PlayerParty17setMemberForOrderENS_12PLAYER_TYPESEi");
    GET_SYMBOL(pl::PlayerParty::setSaveStartCommand, "_ZN2pl11PlayerParty19setSaveStartCommandEii");
    GET_SYMBOL(pl::PlayerParty::weaponOffsetParameter, "_ZN2pl11PlayerParty21weaponOffsetParameterEN3itm13WEAPON_SYSTEME");
    GET_SYMBOL(ScriptEngine::getByte, "_ZN12ScriptEngine7getByteEv");
    GET_SYMBOL(ScriptEngine::getDword, "_ZN12ScriptEngine8getDwordEv");
    GET_SYMBOL(ScriptEngine::jump, "_ZN12ScriptEngine4jumpEj");
    GET_SYMBOL(sys::GameParameter::abilityName, "_ZN3sys13GameParameter11abilityNameEv");
    GET_SYMBOL(sys::GameParameter::changeFormation, "_ZN3sys13GameParameter15changeFormationEv");
    GET_SYMBOL(sys::GameParameter::coverNum, "_ZNK3sys13GameParameter8coverNumEv");
    GET_SYMBOL(sys::GameParameter::Ctor, "_ZN3sys13GameParameterC2Ev");
    GET_SYMBOL(sys::GameParameter::fieldSymbolID, "_ZNK3sys13GameParameter13fieldSymbolIDEv");
    GET_SYMBOL(sys::GameParameter::formation, "_ZN3sys13GameParameter9formationEv");
    GET_SYMBOL(sys::GameParameter::gameClearCount, "_ZN3sys13GameParameter14gameClearCountEv");
    GET_SYMBOL(sys::GameParameter::getBlackChocoboHome, "_ZN3sys13GameParameter19getBlackChocoboHomeER7VecFx32");
    GET_SYMBOL(sys::GameParameter::getDesionDataValidity, "_ZN3sys13GameParameter21getDesionDataValidityEv");
    GET_SYMBOL(sys::GameParameter::getDesionMapName, "_ZN3sys13GameParameter16getDesionMapNameEi");
    GET_SYMBOL(sys::GameParameter::getDesionPosition, "_ZN3sys13GameParameter17getDesionPositionEi");
    GET_SYMBOL(sys::GameParameter::getDesionRot, "_ZN3sys13GameParameter12getDesionRotEiRsS1_S1_");
    GET_SYMBOL(sys::GameParameter::getMagishipMoonChipX, "_ZN3sys13GameParameter20getMagishipMoonChipXEv");
    GET_SYMBOL(sys::GameParameter::getMagishipMoonChipZ, "_ZN3sys13GameParameter20getMagishipMoonChipZEv");
    GET_SYMBOL(sys::GameParameter::getMagishipPosOffsetOnMoonChip, "_ZN3sys13GameParameter30getMagishipPosOffsetOnMoonChipER7VecFx32");
    GET_SYMBOL(sys::GameParameter::getMagshipEarthPos, "_ZN3sys13GameParameter18getMagshipEarthPosER7VecFx32");
    GET_SYMBOL(sys::GameParameter::getMagshipMoonPos, "_ZN3sys13GameParameter17getMagshipMoonPosER7VecFx32");
    GET_SYMBOL(sys::GameParameter::getMapName, "_ZN3sys13GameParameter10getMapNameEv");
    GET_SYMBOL(sys::GameParameter::getPassagePoint2, "_ZN3sys13GameParameter16getPassagePoint2Ei");
    GET_SYMBOL(sys::GameParameter::getSaveNo, "_ZN3sys13GameParameter9getSaveNoEv");
    GET_SYMBOL(sys::GameParameter::getSaveNum, "_ZN3sys13GameParameter10getSaveNumEv");
    GET_SYMBOL(sys::GameParameter::getTVMode, "_ZN3sys13GameParameter9getTVModeEv");
    GET_SYMBOL(sys::GameParameter::getWorldPlayerPosition, "_ZN3sys13GameParameter22getWorldPlayerPositionEv");
    GET_SYMBOL(sys::GameParameter::getWorldPlayerRotation, "_ZN3sys13GameParameter22getWorldPlayerRotationERiS1_S1_");
    GET_SYMBOL(sys::GameParameter::getWorldTelepoMapName, "_ZN3sys13GameParameter21getWorldTelepoMapNameEv");
    GET_SYMBOL(sys::GameParameter::getWorldTelepoPosition, "_ZN3sys13GameParameter22getWorldTelepoPositionEv");
    GET_SYMBOL(sys::GameParameter::getWorldTelepoRotation, "_ZN3sys13GameParameter22getWorldTelepoRotationERiS1_S1_");
    GET_SYMBOL(sys::GameParameter::getWorldVehiclePosition, "_ZN3sys13GameParameter23getWorldVehiclePositionEi");
    GET_SYMBOL(sys::GameParameter::getWorldVehicleRotation, "_ZN3sys13GameParameter23getWorldVehicleRotationEiRiS1_S1_");
    GET_SYMBOL(sys::GameParameter::getWorldVehicleStay, "_ZN3sys13GameParameter19getWorldVehicleStayEi");
    GET_SYMBOL(sys::GameParameter::gold, "_ZN3sys13GameParameter4goldEv");
    GET_SYMBOL(sys::GameParameter::gpCopy, "_ZN3sys13GameParameter6gpCopyEPv");
    GET_SYMBOL(sys::GameParameter::gpInitialize, "_ZN3sys13GameParameter12gpInitializeEv");
    GET_SYMBOL(sys::GameParameter::gpLoadDataReflect, "_ZN3sys13GameParameter17gpLoadDataReflectEv");
    GET_SYMBOL(sys::GameParameter::incrementCoverNum, "_ZN3sys13GameParameter17incrementCoverNumEv");
    GET_SYMBOL(sys::GameParameter::incrementGameClearCount, "_ZN3sys13GameParameter23incrementGameClearCountEv");
    GET_SYMBOL(sys::GameParameter::isAutoMode, "_ZN3sys13GameParameter10isAutoModeEv");
    GET_SYMBOL(sys::GameParameter::isCloudGuideShowed, "_ZNK3sys13GameParameter18isCloudGuideShowedEv");
    GET_SYMBOL(sys::GameParameter::isDash, "_ZN3sys13GameParameter6isDashEv");
    GET_SYMBOL(sys::GameParameter::isPlayVoice, "_ZNK3sys13GameParameter11isPlayVoiceEv");
    GET_SYMBOL(sys::GameParameter::isShowConteEventTelop, "_ZNK3sys13GameParameter21isShowConteEventTelopEv");
    GET_SYMBOL(sys::GameParameter::isTVMode, "_ZN3sys13GameParameter8isTVModeEv");
    GET_SYMBOL(sys::GameParameter::item, "_ZN3sys13GameParameter4itemEv");
    GET_SYMBOL(sys::GameParameter::monsterManiaManager, "_ZN3sys13GameParameter19monsterManiaManagerEv");
    GET_SYMBOL(sys::GameParameter::musicPlayerMode, "_ZN3sys13GameParameter15musicPlayerModeEv");
    GET_SYMBOL(sys::GameParameter::playerName, "_ZN3sys13GameParameter10playerNameEv");
    GET_SYMBOL(sys::GameParameter::playerSaveParameter, "_ZN3sys13GameParameter19playerSaveParameterEN2pl12PLAYER_TYPESE");
    GET_SYMBOL(sys::GameParameter::playTime, "_ZN3sys13GameParameter8playTimeEv");
    GET_SYMBOL(sys::GameParameter::previousSaveData, "_ZN3sys13GameParameter16previousSaveDataEv");
    GET_SYMBOL(sys::GameParameter::prevSaveForFlag, "_ZN3sys13GameParameter15prevSaveForFlagEv");
    GET_SYMBOL(sys::GameParameter::prevSaveForNavimap, "_ZN3sys13GameParameter18prevSaveForNavimapEv");
    GET_SYMBOL(sys::GameParameter::prevSaveForNavimapAsync, "_ZN3sys13GameParameter23prevSaveForNavimapAsyncEv");
    GET_SYMBOL(sys::GameParameter::prevSaveForTime, "_ZN3sys13GameParameter15prevSaveForTimeEv");
    GET_SYMBOL(sys::GameParameter::print, "_ZN3sys13GameParameter5printEv");
    GET_SYMBOL(sys::GameParameter::printMemory, "_ZN3sys13GameParameter11printMemoryEv");
    GET_SYMBOL(sys::GameParameter::reflectForFlag, "_ZN3sys13GameParameter14reflectForFlagEv");
    GET_SYMBOL(sys::GameParameter::reflectForNavimap2, "_ZN3sys13GameParameter18reflectForNavimap2Ev");
    GET_SYMBOL(sys::GameParameter::reflectForTime, "_ZN3sys13GameParameter14reflectForTimeEv");
    GET_SYMBOL(sys::GameParameter::rrc, "_ZN3sys13GameParameter3rrcEv");
    GET_SYMBOL(sys::GameParameter::setAutoMode, "_ZN3sys13GameParameter11setAutoModeEb");
    GET_SYMBOL(sys::GameParameter::setBlackChocoboHome, "_ZN3sys13GameParameter19setBlackChocoboHomeERK7VecFx32");
    GET_SYMBOL(sys::GameParameter::setCloudGuideShowed, "_ZN3sys13GameParameter19setCloudGuideShowedEb");
    GET_SYMBOL(sys::GameParameter::setDash, "_ZN3sys13GameParameter7setDashEb");
    GET_SYMBOL(sys::GameParameter::setDesionDataValidity, "_ZN3sys13GameParameter21setDesionDataValidityEb");
    GET_SYMBOL(sys::GameParameter::setDesionMapName, "_ZN3sys13GameParameter16setDesionMapNameEiPKc");
    GET_SYMBOL(sys::GameParameter::setDesionPosition, "_ZN3sys13GameParameter17setDesionPositionEiR7VecFx32");
    GET_SYMBOL(sys::GameParameter::setDesionRot, "_ZN3sys13GameParameter12setDesionRotEisss");
    GET_SYMBOL(sys::GameParameter::setFieldSymbolID, "_ZN3sys13GameParameter16setFieldSymbolIDEi");
    GET_SYMBOL(sys::GameParameter::setFormation, "_ZN3sys13GameParameter12setFormationEN2pl21PARTY_FORMATION_TYPESE");
    GET_SYMBOL(sys::GameParameter::setMagishipMoonChipX, "_ZN3sys13GameParameter20setMagishipMoonChipXEh");
    GET_SYMBOL(sys::GameParameter::setMagishipMoonChipZ, "_ZN3sys13GameParameter20setMagishipMoonChipZEh");
    GET_SYMBOL(sys::GameParameter::setMagishipPosOffsetOnMoonChip, "_ZN3sys13GameParameter30setMagishipPosOffsetOnMoonChipERK7VecFx32");
    GET_SYMBOL(sys::GameParameter::setMagshipEarthPos, "_ZN3sys13GameParameter18setMagshipEarthPosERK7VecFx32");
    GET_SYMBOL(sys::GameParameter::setMagshipMoonPos, "_ZN3sys13GameParameter17setMagshipMoonPosERK7VecFx32");
    GET_SYMBOL(sys::GameParameter::setMapName, "_ZN3sys13GameParameter10setMapNameEPKc");
    GET_SYMBOL(sys::GameParameter::setMonsterManiaManager, "_ZN3sys13GameParameter22setMonsterManiaManagerERN3mon19MonsterManiaManagerE");
    GET_SYMBOL(sys::GameParameter::setPartsHeaderStr, "_ZN3sys13GameParameter17setPartsHeaderStrEv");
    GET_SYMBOL(sys::GameParameter::setPassagePoint2, "_ZN3sys13GameParameter16setPassagePoint2EiPj");
    GET_SYMBOL(sys::GameParameter::setPlayTime, "_ZN3sys13GameParameter11setPlayTimeEj");
    GET_SYMBOL(sys::GameParameter::setResetCloudGuideShowed, "_ZN3sys13GameParameter24setResetCloudGuideShowedEv");
    GET_SYMBOL(sys::GameParameter::setSaveNo, "_ZN3sys13GameParameter9setSaveNoEh");
    GET_SYMBOL(sys::GameParameter::setSaveNum, "_ZN3sys13GameParameter10setSaveNumEii");
    GET_SYMBOL(sys::GameParameter::setTVMode, "_ZN3sys13GameParameter9setTVModeEi");
    GET_SYMBOL(sys::GameParameter::setWorldPlayerPosition, "_ZN3sys13GameParameter22setWorldPlayerPositionE7VecFx32");
    GET_SYMBOL(sys::GameParameter::setWorldPlayerRotation, "_ZN3sys13GameParameter22setWorldPlayerRotationEiii");
    GET_SYMBOL(sys::GameParameter::setWorldTelepoMapName, "_ZN3sys13GameParameter21setWorldTelepoMapNameEPKc");
    GET_SYMBOL(sys::GameParameter::setWorldTelepoPosition, "_ZN3sys13GameParameter22setWorldTelepoPositionE7VecFx32");
    GET_SYMBOL(sys::GameParameter::setWorldTelepoRotation, "_ZN3sys13GameParameter22setWorldTelepoRotationEiii");
    GET_SYMBOL(sys::GameParameter::setWorldVehiclePosition, "_ZN3sys13GameParameter23setWorldVehiclePositionEi7VecFx32");
    GET_SYMBOL(sys::GameParameter::setWorldVehicleRotation, "_ZN3sys13GameParameter23setWorldVehicleRotationEiiii");
    GET_SYMBOL(sys::GameParameter::setWorldVehicleStay, "_ZN3sys13GameParameter19setWorldVehicleStayEih");
    GET_SYMBOL(sys::GameParameter::summonSaveParameter, "_ZN3sys13GameParameter19summonSaveParameterEv");
    GET_SYMBOL(sys::GGlobal::getCurrentPart, "_ZN3sys7GGlobal14getCurrentPartEv");
    GET_SYMBOL(sys::GGlobal::setNextPart, "_ZN3sys7GGlobal11setNextPartEN4part8GAMEPARTE");
    GET_SYMBOL(title::TitleContents::update, "_ZN5title13TitleContents6updateEv");
    GET_SYMBOL(title::TitleSubState::update, "_ZN5title13TitleSubState6updateEv");
    GET_SYMBOL(ui::CWidgetMng::addWidget, "_ZN2ui10CWidgetMng9addWidgetEiiiiiiii");
    GET_SYMBOL(ui::CWidgetMng::cleanWidget, "_ZN2ui10CWidgetMng11cleanWidgetEv");
    GET_SYMBOL(ui::CWidgetMng::DefaultPadKeyFunc, "_ZN2ui10CWidgetMng17DefaultPadKeyFuncEib");
    GET_SYMBOL(ui::CWidgetMng::DefaultPadKeyFunc_Line2, "_ZN2ui10CWidgetMng23DefaultPadKeyFunc_Line2Eib");
    GET_SYMBOL(ui::CWidgetMng::DefaultPadKeyFunc_Line3, "_ZN2ui10CWidgetMng23DefaultPadKeyFunc_Line3Eib");
    GET_SYMBOL(ui::CWidgetMng::DefaultPadKeyFunc_LineMulti, "_ZN2ui10CWidgetMng27DefaultPadKeyFunc_LineMultiEiib");
    GET_SYMBOL(ui::CWidgetMng::deleteWidget, "_ZN2ui10CWidgetMng12deleteWidgetEPNS_6WidgetE");
    GET_SYMBOL(ui::CWidgetMng::deleteWidgetRange, "_ZN2ui10CWidgetMng12deleteWidgetEii");
    GET_SYMBOL(ui::CWidgetMng::draw, "_ZN2ui10CWidgetMng4drawEv");
    GET_SYMBOL(ui::CWidgetMng::drawWidget, "_ZN2ui10CWidgetMng10drawWidgetEv");
    GET_SYMBOL(ui::CWidgetMng::execute, "_ZN2ui10CWidgetMng7executeEv");
    GET_SYMBOL(ui::CWidgetMng::findWidget, "_ZN2ui10CWidgetMng10findWidgetEi");
    GET_SYMBOL(ui::CWidgetMng::getActiveCursor, "_ZN2ui10CWidgetMng15getActiveCursorEv");
    GET_SYMBOL(ui::CWidgetMng::getActiveCursorItem, "_ZN2ui10CWidgetMng19getActiveCursorItemEv");
    GET_SYMBOL(ui::CWidgetMng::getActiveCursorListMax, "_ZN2ui10CWidgetMng22getActiveCursorListMaxEv");
    GET_SYMBOL(ui::CWidgetMng::getCursorItem, "_ZN2ui10CWidgetMng13getCursorItemEi");
    GET_SYMBOL(ui::CWidgetMng::getListMax, "_ZN2ui10CWidgetMng10getListMaxEi");
    GET_SYMBOL(ui::CWidgetMng::initialize, "_ZN2ui10CWidgetMng10initializeEv");
    GET_SYMBOL(ui::CWidgetMng::moveSlide, "_ZN2ui10CWidgetMng9moveSlideEv");
    GET_SYMBOL(ui::CWidgetMng::moveWidget, "_ZN2ui10CWidgetMng10moveWidgetEv");
    GET_SYMBOL(ui::CWidgetMng::setCursor, "_ZN2ui10CWidgetMng9setCursorEiiiib");
    GET_SYMBOL(ui::CWidgetMng::setDefaultPadKeyFunc, "_ZN2ui10CWidgetMng20setDefaultPadKeyFuncEv");
    GET_SYMBOL(ui::CWidgetMng::setDragState, "_ZN2ui10CWidgetMng12setDragStateEb");
    GET_SYMBOL(ui::CWidgetMng::setListMax, "_ZN2ui10CWidgetMng10setListMaxEii");
    GET_SYMBOL(ui::CWidgetMng::setScroll, "_ZN2ui10CWidgetMng9setScrollEiii");
    GET_SYMBOL(ui::CWidgetMng::setScrollPos, "_ZN2ui10CWidgetMng12setScrollPosEi");
    GET_SYMBOL(ui::CWidgetMng::setScrollRect, "_ZN2ui10CWidgetMng13setScrollRectEiiiii");
    GET_SYMBOL(ui::CWidgetMng::setSlide, "_ZN2ui10CWidgetMng8setSlideEii");
    GET_SYMBOL(ui::CWidgetMng::setWidgetEnable, "_ZN2ui10CWidgetMng15setWidgetEnableEiic");
    GET_SYMBOL(ui::CWidgetMng::setWidgetHilight, "_ZN2ui10CWidgetMng16setWidgetHilightEiii");
    GET_SYMBOL(ui::CWidgetMng::terminate, "_ZN2ui10CWidgetMng9terminateEv");
    GET_SYMBOL(world::canChangeSymbol, "_ZN5world15canChangeSymbolEv");
    GET_SYMBOL(world::disableSPSetting, "_ZN5world16disableSPSettingEPNS_17WorldStateContextE");
    GET_SYMBOL(world::enableSPSetting, "_ZN5world15enableSPSettingEPNS_17WorldStateContextE");
    GET_SYMBOL(world::MSSTextScreenClear, "_ZN5world18MSSTextScreenClearEN3msg6CANVASE");
    GET_SYMBOL(world::searchNextSymbolByCharacterIDBackward, "_ZN5world37searchNextSymbolByCharacterIDBackwardEi");
    GET_SYMBOL(world::searchNextSymbolByCharacterIDForward, "_ZN5world36searchNextSymbolByCharacterIDForwardEi");
    GET_SYMBOL(world::CCameraVibration::ccbUpdate, "_ZN5world16CCameraVibration9ccbUpdateER7VecFx32S2_");
    GET_SYMBOL(world::CCameraVibration::startVibration, "_ZN5world16CCameraVibration14startVibrationENS0_15VIBRATION_STATEEiiiiib");
    GET_SYMBOL(world::MSSConfig::mssInitialize, "_ZN5world9MSSConfig13mssInitializeEv");
    GET_SYMBOL(world::MSSConfig::mssProcess, "_ZN5world9MSSConfig10mssProcessEv");
    GET_SYMBOL(world::WorldState::wsGetString, "_ZN5world10WorldState11wsGetStringEv");
    GET_SYMBOL(world::WorldState::wsSetEnd, "_ZN5world10WorldState8wsSetEndEb");
    GET_SYMBOL(world::WorldStateScheduler::wssAddStateSchedule, "_ZN5world19WorldStateScheduler19wssAddStateScheduleEPKc");
    GET_SYMBOL(world::WorldStateScheduler::wssGetCurrentState, "_ZNK5world19WorldStateScheduler18wssGetCurrentStateEv");
    GET_SYMBOL(world::WorldStateScheduler::wssInitialize, "_ZN5world19WorldStateScheduler13wssInitializeEv");
    GET_SYMBOL(world::WorldTask::deleteTask, "_ZN5world9WorldTask10deleteTaskEPKc");
    GET_SYMBOL(world::WorldTask::queryTask, "_ZN5world9WorldTask9queryTaskEPKc");
    GET_SYMBOL(world::WSMove::wsIsMenuOpen, "_ZN5world6WSMove12wsIsMenuOpenEPNS_17WorldStateContextE");
    GET_SYMBOL(world::WSMove::wsmEncount, "_ZN5world6WSMove10wsmEncountEPNS_17WorldStateContextE");
    GET_SYMBOL(world::WSMove::WSMove, "_ZN5world6WSMoveC1Ev");
    GET_SYMBOL(world::WSVehicleMove::wsProcess, "_ZN5world13WSVehicleMove9wsProcessEPNS_17WorldStateContextE");
    GET_SYMBOL(ys::Condition::isNotBattleCondition, "_ZN2ys9Condition20isNotBattleConditionEv");
    GET_SYMBOL(characterMng, "characterMng");
    GET_SYMBOL(fontScale, "fontScale");
    GET_SYMBOL(g_env, "g_env");
    GET_SYMBOL(LCD_HEIGHT, "LCD_HEIGHT");
    GET_SYMBOL(LCD_WIDTH, "LCD_WIDTH");
    GET_SYMBOL(memCount, "memCount");
    GET_SYMBOL(texCount, "texCount");
    GET_SYMBOL(AchievementCheckFuncs::DecantItemTbl, "_ZN21AchievementCheckFuncs13DecantItemTblE");
    GET_SYMBOL(AchievementContext::instance_, "_ZN18AchievementContext9instance_E");
    GET_SYMBOL(btl::Battle2DManager::instance_, "_ZN3btl15Battle2DManager9instance_E");
    GET_SYMBOL(btl::BattlePart::instance_, "_ZN3btl10BattlePart9instance_E");
    GET_SYMBOL(common::EfficacyDataConvection::instance_, "_ZN6common22EfficacyDataConvection9instance_E");
    GET_SYMBOL(ds::g_Pad, "_ZN2ds5g_PadE");
    GET_SYMBOL(ds::CVram::m_instance, "_ZN2ds5CVram10m_instanceE");
    GET_SYMBOL(ds::snd::g_SoundHeapBGM, "_ZN2ds3snd14g_SoundHeapBGME");
    GET_SYMBOL(ds::snd::g_SoundHeapSE, "_ZN2ds3snd13g_SoundHeapSEE");
    GET_SYMBOL(FlagManager::_instance, "_ZN11FlagManager9_instanceE");
    GET_SYMBOL(itm::ItemManager::instance_, "_ZN3itm11ItemManager9instance_E");
    GET_SYMBOL(map2d::NAVI_MAP_TASK_NAME, "_ZN5map2d18NAVI_MAP_TASK_NAMEE");
    GET_SYMBOL(mon::MonsterManager::instance_, "_ZN3mon14MonsterManager9instance_E");
    GET_SYMBOL(mr::MRDMng, "_ZN2mr6MRDMngE");
    GET_SYMBOL(part::WorldPart::wpInstance_, "_ZN4part9WorldPart11wpInstance_E");
    GET_SYMBOL(pl::LearningAbilityManager::ARRAY_SIZE, "_ZN2pl22LearningAbilityManager10ARRAY_SIZEE");
    GET_SYMBOL(pl::LearningAbilityManager::FLAG_OFFSET, "_ZN2pl22LearningAbilityManager11FLAG_OFFSETE");
    GET_SYMBOL(pl::LearningAbilityManager::FLAG_SIZE, "_ZN2pl22LearningAbilityManager9FLAG_SIZEE");
    GET_SYMBOL(pl::PlayerParty::InvalidPlayer, "_ZN2pl11PlayerParty13InvalidPlayerE");
    GET_SYMBOL(pl::PlayerParty::playerPartyInstance_, "_ZN2pl11PlayerParty20playerPartyInstance_E");
    GET_SYMBOL(sys::GameParameter::gpInstance_, "_ZN3sys13GameParameter11gpInstance_E");
    GET_SYMBOL(sys::GGlobal::heapBGM_, "_ZN3sys7GGlobal8heapBGM_E");
    GET_SYMBOL(sys::GGlobal::heapSE_, "_ZN3sys7GGlobal7heapSE_E");
    GET_SYMBOL(sys::GGlobal::heapSound_, "_ZN3sys7GGlobal10heapSound_E");
    GET_SYMBOL(ui::g_WidgetMng, "_ZN2ui11g_WidgetMngE");
}
#undef GET_SYMBOL
} // namespace babil
